// Ported from CarbonEngine (MIT, (c) 2026 CCP Games) - https://github.com/carbonengine/trinity
//   trinity/trinity/Shader/Tr2Effect.h
// Generated by format-carbon carbon-class --emit. Verify against shader/Tr2ConstantEffectParameter.json.
import { io, type } from "@carbonenginejs/runtime-utils/schema";
import { vec4 } from "@carbonenginejs/runtime-utils/vec4";
import { CjsParameter } from "./CjsParameter.js";

/** Tr2ConstantEffectParameter (shader) - generated from schema shapeHash b4e14ee0.... */
@type.define({ className: "Tr2ConstantEffectParameter", family: "shader" })
export class Tr2ConstantEffectParameter extends CjsParameter
{

  /** name (BlueSharedString) - persisted via the constParameters structure list. */
  @io.rebuild("bindings")
  @io.persist
  @type.string
  name = "";

  /** value (Vector4) - persisted via the constParameters structure list. */
  @io.rebuild("bindings")
  @io.persist
  @type.vec4
  value = vec4.create();

}
