// Ported from CarbonEngine (MIT, (c) 2026 CCP Games) - https://github.com/carbonengine/trinity
//   trinity/trinity/Shader/Tr2Effect.h
// Generated by format-carbon carbon-class --emit. Verify against shader/Tr2ConstantEffectParameter.json.
import { type } from "@carbonenginejs/core-types/schema";
import { vec4 } from "@carbonenginejs/core-math/vec4";
import { CjsShaderParameter } from "./CjsShaderParameter.js";

/** Tr2ConstantEffectParameter (shader) - generated from schema shapeHash b4e14ee0.... */
@type.define({ className: "Tr2ConstantEffectParameter", family: "shader" })
export class Tr2ConstantEffectParameter extends CjsShaderParameter
{

  /** name (BlueSharedString) */
  @type.string
  name = "";

  /** value (Vector4) */
  @type.vec4
  value = vec4.create();

}
