// Ported from CarbonEngine (MIT, (c) 2026 CCP Games) - https://github.com/carbonengine/trinity
//   trinity/trinity/Shader/Parameter/Tr2GeometryBufferParameter.h
// Generated by format-carbon carbon-class --emit. Verify against shader/Tr2GeometryBufferParameter.json.
import { carbon, impl, io, type } from "@carbonenginejs/core-types/schema";
import { CjsModel } from "@carbonenginejs/core-types/model";
import { CjsShaderParameter } from "./CjsShaderParameter.js";

/** Tr2GeometryBufferParameter (shader) - generated from schema shapeHash bc9ed4c6.... */
@type.define({ className: "Tr2GeometryBufferParameter", family: "shader" })
export class Tr2GeometryBufferParameter extends CjsShaderParameter
{

  /** m_resourcePath (std::wstring) [READWRITE, NOTIFY, PERSIST] */
  @io.flag("resource")
  @io.notify
  @io.persist
  @type.string
  resourcePath = "";

  /** m_gpuBuffer (ITr2GpuBufferPtr) [READWRITE, PERSIST, NOTIFY] */
  @io.notify
  @io.persist
  @type.objectRef("ITr2GpuBuffer")
  gpuBuffer = null;

  /** m_isUsedByEffect (bool) [READ] */
  @io.read
  @type.boolean
  usedByCurrentEffect = false;

  /** m_meshIndex (int32_t) [READWRITE, NOTIFY, PERSIST] */
  @io.notify
  @io.persist
  @type.int32
  meshIndex = 0;

  /** m_name (BlueSharedString) [READWRITE, NOTIFY, PERSIST] */
  @io.notify
  @io.persist
  @type.string
  name = "";

  cachedEffect = null;

  @carbon.method
  @impl.implemented
  GetParameterName()
  {
    return this.name;
  }

  @carbon.method
  @impl.adapted
  Initialize()
  {
    return true;
  }

  @carbon.method
  @impl.adapted
  OnModified(_options = {})
  {
    if (this.__state.flags.delete("resource"))
    {
      this.Initialize();
      this.RebuildEffectHandles(this.cachedEffect);
    }
    return true;
  }

  @carbon.method
  @impl.adapted
  RebuildEffectHandles(effectRes)
  {
    this.cachedEffect = effectRes;
    this.usedByCurrentEffect = !!this.name && !!CjsShaderParameter.getEffectResource(effectRes, this.name);
  }

  @carbon.method
  @impl.adapted
  CopyToResourceSet()
  {
    return false;
  }

  @carbon.method
  @impl.adapted
  ApplyUav()
  {
    return false;
  }

  @carbon.method
  @impl.implemented
  IsValid()
  {
    return !!this.gpuBuffer;
  }

  @carbon.method
  @impl.implemented
  SetGpuBuffer(buffer)
  {
    this.resourcePath = "";
    this.gpuBuffer = buffer;
  }

  @carbon.method
  @impl.implemented
  GetGpuBuffer()
  {
    return this.gpuBuffer;
  }

}
