// Ported from CarbonEngine (MIT, (c) 2026 CCP Games) - https://github.com/carbonengine/trinity
//   trinity/trinity/Shader/Parameter/Tr2TextureAnimationParameter.h
// Generated by format-carbon carbon-class --emit. Verify against shader/Tr2TextureAnimationParameter.json.
import { carbon, impl, io, type } from "@carbonenginejs/core-types/schema";
import { CjsParameter } from "./CjsParameter.js";

/** Tr2TextureAnimationParameter (shader) - generated from schema shapeHash 609a4065.... */
@type.define({ className: "Tr2TextureAnimationParameter", family: "shader" })
export class Tr2TextureAnimationParameter extends CjsParameter
{

  /** m_animation (Tr2TextureAnimationPtr) [READWRITE, PERSIST, NOTIFY] */
  @io.notify
  @io.persist
  @type.objectRef("Tr2TextureAnimation")
  animation = null;

  /** m_channel (BlueSharedString) [READWRITE, PERSIST] */
  @io.persist
  @type.string
  channel = "";

  /** m_name (BlueSharedString) [READWRITE, PERSIST] */
  @io.persist
  @type.string
  name = "";

  resourceType = 0;

  #materials = [];

  @carbon.method
  @impl.implemented
  GetParameterName()
  {
    return this.name;
  }

  @carbon.method
  @impl.adapted
  OnModified(_options = {})
  {
    for (const material of this.#materials)
    {
      CjsParameter.markMaterialResourcesDirty(material);
    }
    return true;
  }

  @carbon.method
  @impl.adapted
  RebuildEffectHandles(effectRes)
  {
    const resource = this.name ? CjsParameter.getEffectResource(effectRes, this.name) : null;
    if (resource)
    {
      this.resourceType = resource.type ?? this.resourceType;
    }
  }

  @carbon.method
  @impl.adapted
  CopyToResourceSet()
  {
    return false;
  }

  @carbon.method
  @impl.implemented
  ApplyUav()
  {
    return false;
  }

  @carbon.method
  @impl.implemented
  OnAddedToMaterial(material)
  {
    if (!this.#materials.includes(material))
    {
      this.#materials.push(material);
    }
  }

  @carbon.method
  @impl.implemented
  OnRemovedFromMaterial(material)
  {
    const index = this.#materials.indexOf(material);
    if (index >= 0)
    {
      this.#materials.splice(index, 1);
    }
  }

  @carbon.method
  @impl.adapted
  GetTexture()
  {
    return this.animation?.GetTexture?.(this.channel) ?? this.animation?.getTexture?.(this.channel) ?? null;
  }

}
