// Ported from CarbonEngine (MIT, (c) 2026 CCP Games) - https://github.com/carbonengine/trinity
//   trinity/trinity/Shader/Parameter/TriTransformParameter.h
// Generated by format-carbon carbon-class --emit. Verify against shader/TriTransformParameter.json.
import { carbon, impl, io, schema, type } from "@carbonenginejs/core-types/schema";
import { mat4 } from "@carbonenginejs/core-math/mat4";
import { quat } from "@carbonenginejs/core-math/quat";
import { vec3 } from "@carbonenginejs/core-math/vec3";
import { CjsShaderParameter } from "./CjsShaderParameter.js";

/** TriTransformParameter (shader) - generated from schema shapeHash de073c4a.... */
@type.define({ className: "TriTransformParameter", family: "shader" })
export class TriTransformParameter extends CjsShaderParameter
{

  /** m_transformBase (TRITRANSFORMBASE - enum TRITRANSFORMBASE) [READWRITE, PERSIST, ENUM] */
  @io.persist
  @type.int32
  @schema.enum("TRITRANSFORMBASE")
  transformBase = 0;

  /** m_rotationCenter (Vector3) [READWRITE, PERSIST] */
  @io.persist
  @type.vec3
  rotationCenter = vec3.create();

  /** m_name (BlueSharedString) [READWRITE, PERSIST] */
  @io.persist
  @type.string
  name = "";

  /** m_rotation (Quaternion) [READWRITE, PERSIST] */
  @io.persist
  @type.quat
  rotation = quat.create();

  /** m_scaling (Vector3) [READWRITE, PERSIST] */
  @io.persist
  @type.vec3
  scaling = vec3.fromValues(1, 1, 1);

  /** m_translation (Vector3) [READWRITE, PERSIST] */
  @io.persist
  @type.vec3
  translation = vec3.create();

  /** m_worldTransform (Matrix) [READWRITE, PERSIST] */
  @io.persist
  @type.mat4
  worldTransform = mat4.create();

  @carbon.method
  @impl.implemented
  GetParameterName()
  {
    return this.name;
  }

  @carbon.method
  @impl.adapted
  CopyValueToEffect(_inputType, dest, size = 64, context = null)
  {
    const transform = mat4.create();
    mat4.fromRotationTranslationScaleOrigin(transform, this.rotation, this.translation, this.scaling, this.rotationCenter);
    const base = context?.inverseViewTransform ?? context?.GetInverseViewTransform?.() ?? null;
    if (base && this.transformBase !== 0)
    {
      const baseTransform = mat4.clone(base);
      baseTransform[12] = 0;
      baseTransform[13] = 0;
      baseTransform[14] = 0;
      mat4.multiply(transform, baseTransform, transform);
    }
    const out = mat4.create();
    mat4.transpose(out, transform);
    const count = Math.min(16, Math.floor(Number(size) / 4) || 16, dest?.length ?? 16);
    for (let i = 0; i < count; i++)
    {
      dest[i] = out[i];
    }
  }

}
