// Ported from CarbonEngine (MIT, (c) 2026 CCP Games) - https://github.com/carbonengine/trinity
//   trinity/trinity/Shader/Parameter/TriVariableParameter.h
// Generated by format-carbon carbon-class --emit. Verify against shader/TriVariableParameter.json.
import { carbon, impl, io, type } from "@carbonenginejs/runtime-utils/schema";
import { CjsModel } from "@carbonenginejs/runtime-utils/model";
import { CjsParameter } from "./CjsParameter.js";

/** TriVariableParameter (shader) - generated from schema shapeHash c1071754.... */
@type.define({ className: "TriVariableParameter", family: "shader" })
export class TriVariableParameter extends CjsParameter
{

  /** m_name (BlueSharedString) [READWRITE, NOTIFY, PERSIST] */
  @io.flag("effectHandles")
  @io.notify
  @io.persist
  @type.string
  name = "";

  /** m_isUsedByEffect (bool) [READ] */
  @io.read
  @type.boolean
  usedByCurrentTechnique = false;

  /** m_isUsedByEffect (bool) [READ] */
  @io.read
  @type.boolean
  usedByCurrentEffect = false;

  /** m_variableName (BlueSharedString) [READWRITE, NOTIFY, PERSIST] */
  @io.flag("variable")
  @io.notify
  @io.persist
  @type.string
  variableName = "";

  variable = null;

  variableStore = null;

  cachedEffect = null;

  @carbon.method
  @impl.implemented
  GetParameterName()
  {
    return this.name;
  }

  /** Content hash: name only - the variable's value comes from the store. */
  @carbon.method
  @impl.adapted
  GetHashValue(startingHash = CjsParameter.FNV1_INITIAL)
  {
    return CjsParameter.hashFnv1String(this.name, startingHash);
  }

  @carbon.method
  @impl.adapted
  Initialize(variableStore = null)
  {
    this.variableStore = variableStore ?? this.variableStore;
    if (!this.variableName)
    {
      this.variable = null;
      return true;
    }
    this.variable = this.variableStore?.GetVariable?.(this.variableName) ?? this.variableStore?.getVariable?.(this.variableName) ?? this.variableStore?.[this.variableName] ?? this.variable;
    return true;
  }

  @carbon.method
  @impl.adapted
  OnModified(_options = {})
  {
    const flags = this.__state.flags;
    if (flags.delete("variable"))
    {
      this.Initialize(this.variableStore);
    }
    if (flags.delete("effectHandles"))
    {
      this.RebuildEffectHandles(this.cachedEffect);
    }
    return true;
  }

  @carbon.method
  @impl.adapted
  RebuildEffectHandles(effectRes)
  {
    this.cachedEffect = effectRes;
    this.usedByCurrentEffect = false;
    this.usedByCurrentTechnique = false;
    if (!this.name || !effectRes || !this.variable)
    {
      return;
    }
    const type = this.GetVariableType();
    const isResource = type === "texture" || type === "textureRes" || type === "gpuBuffer" || type === 4 || type === 5;
    const used = isResource ? !!CjsParameter.getEffectResource(effectRes, this.name) : !!CjsParameter.getEffectConstant(effectRes, this.name);
    this.usedByCurrentEffect = used;
    this.usedByCurrentTechnique = used;
  }

  @carbon.method
  @impl.adapted
  CopyValueToEffect(inputType, dest, size, renderContext)
  {
    this.variable?.CopyValueToEffect?.(inputType, dest, size, renderContext);
  }

  @carbon.method
  @impl.adapted
  CopyToResourceSet()
  {
    return false;
  }

  @carbon.method
  @impl.adapted
  ApplyUav()
  {
    return false;
  }

  @carbon.method
  @impl.implemented
  GetVariableType()
  {
    return this.variable?.GetType?.() ?? this.variable?.type ?? "invalid";
  }

}
