// Ported from CarbonEngine (MIT, (c) 2026 CCP Games) - https://github.com/carbonengine/trinity
//   trinity/trinity/Shader/Tr2Material.h
// Generated by format-carbon carbon-class --emit. Verify against shader/Tr2EffectLibraryParameters.json.
import { type } from "@carbonenginejs/core-types/schema";
import { CjsModel } from "@carbonenginejs/core-types/model";
import { Tr2MaterialStageInput } from "./Tr2MaterialStageInput.js";

/** Tr2EffectLibraryParameters (shader) - generated from schema shapeHash b0b10bab.... */
@type.define({ className: "Tr2EffectLibraryParameters", family: "shader" })
export class Tr2EffectLibraryParameters extends CjsModel
{

  /** m_localInput (Tr2MaterialStageInput) */
  @type.rawStruct("Tr2MaterialStageInput")
  localInput = new Tr2MaterialStageInput();

  /** m_globalInput (Tr2MaterialStageInput) */
  @type.rawStruct("Tr2MaterialStageInput")
  globalInput = new Tr2MaterialStageInput();

  /** m_globalResourceSetDesc (Tr2ResourceSetDescriptionAL) */
  @type.rawStruct("Tr2ResourceSetDescriptionAL")
  globalResourceSetDesc = null;

  /** m_globalResourceSet (Tr2ResourceSetAL) */
  @type.rawStruct("Tr2ResourceSetAL")
  globalResourceSet = null;

  /** m_reroutedParameters (std::vector<ITriReroutable*>) */
  @type.list("ITriReroutable")
  reroutedParameters = [];

  /** m_usedResources (std::vector<ITr2EffectValuePtr>) */
  @type.list("ITr2EffectValue")
  usedResources = [];

  /** m_usedTextures (Tr2BindlessResourcesAL) */
  @type.rawStruct("Tr2BindlessResourcesAL")
  usedTextures = null;

  /** m_globalResourceSetDirty (bool) */
  @type.boolean
  globalResourceSetDirty = true;

  /** m_usedTexturesDirty (bool) */
  @type.boolean
  usedTexturesDirty = false;

  AddUsedResource(resource)
  {
    this.usedResources.push(resource);
    this.usedTexturesDirty = true;
  }

  AddReroutable(reroutable)
  {
    this.reroutedParameters.push(reroutable);
  }

}
