// Ported from CarbonEngine (MIT, (c) 2026 CCP Games) - https://github.com/carbonengine/trinity
//   trinity/trinity/Shader/Tr2Material.h
// Generated by format-carbon carbon-class --emit. Verify against shader/Tr2EffectTechniqueInputs.json.
import { type } from "@carbonenginejs/runtime-utils/schema";
import { CjsModel } from "@carbonenginejs/runtime-utils/model";

/** Tr2EffectTechniqueInputs (shader) - generated from schema shapeHash 6ea72a37.... */
@type.define({ className: "Tr2EffectTechniqueInputs", family: "shader" })
export class Tr2EffectTechniqueInputs extends CjsModel
{

  /** passes (std::vector<std::unique_ptr<Tr2EffectPassParameters>>) */
  @type.list("Tr2EffectPassParameters")
  passes = [];

  /** libraries (std::vector<std::unique_ptr<Tr2EffectLibraryParameters>>) */
  @type.list("Tr2EffectLibraryParameters")
  libraries = [];

}
