// Ported from CarbonEngine (MIT, (c) 2026 CCP Games) - https://github.com/carbonengine/trinity
//   trinity/trinity/Shader/Tr2Material.h
// Generated by format-carbon carbon-class --emit. Verify against shader/Tr2EffectParam.json.
import { type } from "@carbonenginejs/core-types/schema";
import { CjsModel } from "@carbonenginejs/core-types/model";

/** Tr2EffectParam (shader) - generated from schema shapeHash fdbc3137.... */
@type.define({ className: "Tr2EffectParam", family: "shader" })
export class Tr2EffectParam extends CjsModel
{

  /** m_sourceName (std::string) */
  @type.string
  sourceName = "";

  /** m_sourceValue (ITr2EffectValuePtr) */
  @type.objectRef("ITr2EffectValue")
  sourceValue = null;

  /** m_registerIndex (unsigned int) */
  @type.uint32
  registerIndex = 0;

  /** m_registerCount (unsigned int) */
  @type.uint32
  registerCount = 0;

}
