// Ported from CarbonEngine (MIT, (c) 2026 CCP Games) - https://github.com/carbonengine/trinity
//   trinity/trinity/Shader/Tr2Material.h
// Generated by format-carbon carbon-class --emit. Verify against shader/Tr2EffectPassParameters.json.
import { type } from "@carbonenginejs/core-types/schema";
import { CjsModel } from "@carbonenginejs/core-types/model";
import { Tr2MaterialStageInput } from "./Tr2MaterialStageInput.js";

/** Tr2EffectPassParameters (shader) - generated from schema shapeHash 5e017ea9.... */
@type.define({ className: "Tr2EffectPassParameters", family: "shader" })
export class Tr2EffectPassParameters extends CjsModel
{

  /** m_stageInput (Tr2MaterialStageInput) */
  @type.rawStruct("Tr2MaterialStageInput")
  stageInput = Array.from({ length: 6 }, () => new Tr2MaterialStageInput());

  /** m_reroutedParameters (std::vector<ITriReroutable*>) */
  @type.list("ITriReroutable")
  reroutedParameters = [];

  /** m_resourceSetDesc (Tr2ResourceSetDescriptionAL) */
  @type.rawStruct("Tr2ResourceSetDescriptionAL")
  resourceSetDesc = null;

  /** m_resourceSet (Tr2ResourceSetAL) */
  @type.rawStruct("Tr2ResourceSetAL")
  resourceSet = null;

  /** m_usedResources (std::vector<ITr2EffectValuePtr>) */
  @type.list("ITr2EffectValue")
  usedResources = [];

  /** m_usedTextures (Tr2BindlessResourcesAL) */
  @type.rawStruct("Tr2BindlessResourcesAL")
  usedTextures = null;

  /** m_resourceSetHash (uint32_t) */
  @type.uint32
  resourceSetHash = 0;

  /** m_resourceSetDirty (bool) */
  @type.boolean
  resourceSetDirty = true;

  /** m_compatibleWithGdr (bool) */
  @type.boolean
  compatibleWithGdr = true;

  /** m_usedTexturesDirty (bool) */
  @type.boolean
  usedTexturesDirty = false;

  AddUsedResource(resource)
  {
    this.usedResources.push(resource);
    this.usedTexturesDirty = true;
  }

  AddReroutable(reroutable)
  {
    this.reroutedParameters.push(reroutable);
  }

  AllocateConstantMirror(type, size)
  {
    this.#stage(type).AllocateConstants(size);
  }

  GetSharedConstantBuffer(type, contents, size)
  {
    this.#stage(type).GetSharedConstantBuffer(contents, size);
  }

  #stage(type)
  {
    const index = Math.max(0, Number(type) || 0);
    this.stageInput[index] ??= new Tr2MaterialStageInput();
    return this.stageInput[index];
  }

}
