// Ported from CarbonEngine (MIT, (c) 2026 CCP Games) - https://github.com/carbonengine/trinity
//   trinity/trinity/Shader/Tr2Material.h
// Generated by format-carbon carbon-class --emit. Verify against shader/Tr2MaterialStageInput.json.
import { type } from "@carbonenginejs/runtime-utils/schema";
import { CjsModel } from "@carbonenginejs/runtime-utils/model";

/** Tr2MaterialStageInput (shader) - generated from schema shapeHash 8bae330e.... */
@type.define({ className: "Tr2MaterialStageInput", family: "shader" })
export class Tr2MaterialStageInput extends CjsModel
{

  /** m_constantBufferDirty (bool) */
  @type.boolean
  constantBufferDirty = false;

  /** m_sharedBufferKey (Tr2SharedConstantBuffers::Key) */
  @type.rawStruct("Tr2SharedConstantBuffers::Key")
  sharedBufferKey = null;

  /** m_shaderParameters (Tr2EffectParamVector) */
  @type.list("Tr2EffectParam")
  shaderParameters = [];

  /** m_shaderParametersWithNotification (Tr2EffectParamVector) */
  @type.list("Tr2EffectParam")
  shaderParametersWithNotification = [];

  /** m_textures (Tr2EffectParamVector) */
  @type.list("Tr2EffectParam")
  textures = [];

  /** m_uavs (Tr2EffectParamVector) */
  @type.list("Tr2EffectParam")
  uavs = [];

  /** m_constantBuffer (Tr2ConstantBufferAL) */
  @type.rawStruct("Tr2ConstantBufferAL")
  constantBuffer = null;

  /** m_constantMirror (CcpMallocBuffer) */
  @type.rawStruct("CcpMallocBuffer")
  constantMirror = null;

  AllocateConstants(size = 0)
  {
    const byteSize = Math.max(0, Number(size) || 0);
    const alignedSize = byteSize % 16 ? byteSize + 16 - byteSize % 16 : byteSize;
    this.constantMirror = alignedSize ? new Uint8Array(alignedSize) : null;
    this.constantBufferDirty = alignedSize > 0;
  }

  GetSharedConstantBuffer(contents, size = contents?.byteLength ?? contents?.length ?? 0)
  {
    const byteSize = Math.max(0, Number(size) || 0);
    this.constantMirror = byteSize ? Tr2MaterialStageInput.copyBytes(contents, byteSize) : null;
    this.constantBufferDirty = false;
  }

  static copyBytes(contents, size)
  {
    const out = new Uint8Array(size);
    if (contents instanceof ArrayBuffer)
    {
      out.set(new Uint8Array(contents, 0, Math.min(size, contents.byteLength)));
    }
    else if (ArrayBuffer.isView(contents))
    {
      out.set(new Uint8Array(contents.buffer, contents.byteOffset, Math.min(size, contents.byteLength)));
    }
    else if (contents && typeof contents.length === "number")
    {
      out.set(Array.from(contents).slice(0, size));
    }
    return out;
  }

}
