// Ported from CarbonEngine (MIT, (c) 2026 CCP Games) - https://github.com/carbonengine/trinity
//   trinity/trinity/Shader/Tr2ShaderBuffer.h
// Generated by format-carbon carbon-class --emit. Verify against shader/Tr2ShaderBuffer.json.
import { carbon, impl, io, type } from "@carbonenginejs/core-types/schema";
import { CjsModel } from "@carbonenginejs/core-types/model";

/** Tr2ShaderBuffer (shader) - generated from schema shapeHash 977c582f.... */
@type.define({ className: "Tr2ShaderBuffer", family: "shader" })
export class Tr2ShaderBuffer extends CjsModel
{

  /** m_size (int) [READ] */
  @io.read
  @type.int32
  size = 0;

  data = null;

  shaderType = 1;

  /** Carbon method SetData -> SetDataFromScript (MAP_METHOD_AND_WRAP). */
  @carbon.method
  @impl.implemented
  SetData(data, size = data?.byteLength ?? data?.length ?? 0)
  {
    const byteSize = Math.max(0, Number(size) || 0);
    if (!byteSize)
    {
      this.data = null;
      this.size = 0;
      return;
    }
    this.data = Tr2ShaderBuffer.copyBytes(data, byteSize);
    this.size = byteSize;
  }

  SetShaderType(shaderType)
  {
    this.shaderType = Number(shaderType) || 0;
  }

  ApplyBuffer()
  {
    return false;
  }

  static copyBytes(data, size)
  {
    const out = new Uint8Array(size);
    if (data instanceof ArrayBuffer)
    {
      out.set(new Uint8Array(data, 0, Math.min(size, data.byteLength)));
    }
    else if (ArrayBuffer.isView(data))
    {
      out.set(new Uint8Array(data.buffer, data.byteOffset, Math.min(size, data.byteLength)));
    }
    else if (typeof data === "string")
    {
      for (let i = 0; i < Math.min(size, data.length); i++)
      {
        out[i] = data.charCodeAt(i) & 0xff;
      }
    }
    else if (data && typeof data.length === "number")
    {
      out.set(Array.from(data).slice(0, size));
    }
    return out;
  }

}
