// Ported from CarbonEngine (MIT, (c) 2026 CCP Games) - https://github.com/carbonengine/trinity
//   trinity/trinity/Shader/Tr2Material.h
// Generated by format-carbon carbon-class --emit. Verify against shader/Tr2Material.json.
import { type } from "@carbonenginejs/core-types/schema";
import { CjsModel } from "@carbonenginejs/core-types/model";

/** Tr2Material (shader) - generated from schema shapeHash 4fb63b7e.... */
@type.define({ className: "Tr2Material", family: "shader" })
export class Tr2Material extends CjsModel
{

  /** m_shader (Tr2ShaderPtr) */
  @type.objectRef("Tr2Shader")
  shader = null;

  /** m_parametersForPasses (Tr2EffectTechniqueParametersVector) */
  @type.list("Tr2EffectTechniqueParameters")
  parametersForPasses = [];

  /** m_parametersForLibraries (Tr2EffectTechniqueParametersVector) */
  @type.list("Tr2EffectTechniqueParameters")
  parametersForLibraries = [];

  /** m_lodTextureParameters (std::vector<ITriEffectTextureParameterPtr>) */
  @type.list("ITriEffectTextureParameter")
  lodTextureParameters = [];

  /** m_resourceSetHash (mutable uint32_t) */
  @type.uint32
  resourceSetHash = 0;

  /** m_compatibleWithGdr (bool) */
  @type.boolean
  compatibleWithGdr = false;

  GetSortValue()
  {
    return this.resourceSetHash;
  }

  GetShaderStateInterface()
  {
    return this.shader;
  }

  GetPassDescription(techniqueIndex = 0, passIndex = 0)
  {
    return this.parametersForPasses?.[techniqueIndex]?.passes?.[passIndex] ?? null;
  }

  InvalidateResourceSets()
  {
    for (const technique of this.parametersForPasses)
    {
      for (const pass of technique?.passes ?? [])
      {
        pass.resourceSetHash = 0;
        pass.resourceSetDirty = true;
        pass.usedTexturesDirty = true;
      }
      for (const library of technique?.libraries ?? [])
      {
        library.usedTexturesDirty = true;
      }
    }
    this.resourceSetHash = 0;
  }

  ResourceChanged()
  {
    for (const technique of this.parametersForPasses)
    {
      for (const pass of technique?.passes ?? [])
      {
        pass.resourceSetHash = 0;
        pass.resourceSetDirty = true;
        pass.usedTexturesDirty = true;
      }
      for (const library of technique?.libraries ?? [])
      {
        library.usedTexturesDirty = true;
      }
    }
    this.resourceSetHash = 0;
  }

  MarkConstantBuffersDirty()
  {
    for (const technique of this.parametersForPasses)
    {
      for (const pass of technique?.passes ?? [])
      {
        for (const stage of pass?.stageInput ?? [])
        {
          if (stage?.shaderParametersWithNotification?.length)
          {
            stage.constantBufferDirty = true;
          }
        }
      }
      for (const library of technique?.libraries ?? [])
      {
        if (library?.globalInput?.shaderParametersWithNotification?.length)
        {
          library.globalInput.constantBufferDirty = true;
        }
        if (library?.localInput?.shaderParametersWithNotification?.length)
        {
          library.localInput.constantBufferDirty = true;
        }
      }
    }
    this.resourceSetHash = 0;
  }

  UsedWithScreenSize(screenSize, worldRadius, uvDensities = [])
  {
    for (const value of this.lodTextureParameters)
    {
      value?.UsedWithScreenSize?.(screenSize, worldRadius, uvDensities);
    }
  }

  CompatibleWithGdr(techniqueName = null)
  {
    if (techniqueName === null)
    {
      return this.compatibleWithGdr;
    }
    const techniqueIndex = this.shader?.GetTechniqueIndex?.(techniqueName) ?? -1;
    if (techniqueIndex < 0)
    {
      return false;
    }
    return (this.parametersForPasses?.[techniqueIndex]?.passes ?? []).every(pass => pass?.compatibleWithGdr !== false);
  }

}
