// Ported from CarbonEngine (MIT, (c) 2026 CCP Games) - https://github.com/carbonengine/trinity
//   trinity/trinity/Shader/Tr2Shader.h
// Generated by format-carbon carbon-class --emit. Verify against shader/Tr2Shader.json.
import { type } from "@carbonenginejs/runtime-utils/schema";
import { CjsModel } from "@carbonenginejs/runtime-utils/model";
import { Tr2EffectDescription } from "./reflection/Tr2EffectDescription.js";

/** Tr2Shader (shader) - generated from schema shapeHash 39e1616a.... */
@type.define({ className: "Tr2Shader", family: "shader" })
export class Tr2Shader extends CjsModel
{

  /** m_sortValue (unsigned int) */
  @type.uint32
  sortValue = 0;

  /** m_effect (Tr2EffectDescription) */
  @type.rawStruct("Tr2EffectDescription")
  effect = new Tr2EffectDescription();

  /** m_hasVertexBufferAccessInRtShadow (bool) */
  @type.boolean
  hasVertexBufferAccessInRtShadow = false;

  GetTechniqueIndex(name = "Main")
  {
    const techniques = this.effect?.techniques ?? [];
    if (!techniques.length)
    {
      return -1;
    }
    if (name === "ANY_TECHNIQUE" || name === "Any" || name === "")
    {
      return 0;
    }
    return techniques.findIndex(technique => technique?.name === name);
  }

  GetPassCount(techniqueIndex = 0)
  {
    return this.effect?.techniques?.[techniqueIndex]?.passes?.length ?? 0;
  }

  GetConstant(name)
  {
    return Tr2Shader.findStageValue(this.effect, name, "constants");
  }

  GetResource(name)
  {
    return Tr2Shader.findStageValue(this.effect, name, "resources") ?? Tr2Shader.findStageValue(this.effect, name, "uavs");
  }

  GetParameterAnnotations(parameterName)
  {
    return Tr2Shader.findAnnotationSet(this.effect?.annotations, parameterName);
  }

  GetSortValue()
  {
    return this.sortValue;
  }

  GetEffectDescription()
  {
    return this.effect;
  }

  GetEffect()
  {
    return this.effect;
  }

  GetShaderTypeMask(techniqueIndex = 0)
  {
    return Number(this.effect?.techniques?.[techniqueIndex]?.shaderTypeMask ?? 0);
  }

  ProcessEffect()
  {
    this.sortValue = 0;
    const pass = this.effect?.techniques?.[0]?.passes?.[0];
    if (!pass)
    {
      return;
    }
    const stages = pass.stageInputs ?? [];
    const pixelShader = Number(stages[1]?.shader ?? stages[1]?.m_shader ?? 0) & 0x3ff;
    const vertexShader = Number(stages[0]?.shader ?? stages[0]?.m_shader ?? 0) & 0x3ff;
    const renderStates = Number(pass.renderStates ?? 0) & 0x3ff;
    const passCount = Number(this.effect?.techniques?.[0]?.passes?.length ?? 0) & 0x3;
    this.sortValue = (passCount << 30) | (pixelShader << 20) | (vertexShader << 10) | renderStates;
  }

  HasVertexBufferAccessInRtShadow()
  {
    return this.hasVertexBufferAccessInRtShadow;
  }

  static findStageValue(effect, name, key)
  {
    for (const stage of Tr2Shader.iterateStages(effect))
    {
      const values = stage?.[key];
      const found = Tr2Shader.findNamedCollectionValue(values, name);
      if (found)
      {
        return found;
      }
    }
    return null;
  }

  static iterateStages(effect)
  {
    const stages = [];
    for (const technique of effect?.techniques ?? [])
    {
      for (const pass of technique?.passes ?? [])
      {
        stages.push(...pass?.stageInputs ?? []);
      }
      for (const library of technique?.libraries ?? [])
      {
        if (library?.globalInput)
        {
          stages.push(library.globalInput);
        }
        if (library?.localInput)
        {
          stages.push(library.localInput);
        }
      }
    }
    return stages;
  }

  static findNamedCollectionValue(values, name)
  {
    if (!values)
    {
      return null;
    }
    if (Array.isArray(values))
    {
      return values.find(value => value?.name === name || value?.[1]?.name === name) ?? null;
    }
    if (values instanceof Map)
    {
      for (const value of values.values())
      {
        if (value?.name === name)
        {
          return value;
        }
      }
      return null;
    }
    for (const value of Object.values(values))
    {
      if (value?.name === name)
      {
        return value;
      }
    }
    return null;
  }

  static findAnnotationSet(annotations, parameterName)
  {
    if (!annotations)
    {
      return null;
    }
    if (annotations instanceof Map)
    {
      return annotations.get(parameterName) ?? null;
    }
    if (Array.isArray(annotations))
    {
      const entry = annotations.find(item => item?.name === parameterName || item?.[0] === parameterName);
      return entry?.annotations ?? entry?.value ?? entry?.[1] ?? null;
    }
    return annotations[parameterName] ?? null;
  }

}
