// Generated by format-carbon carbon-class --emit-enums from schema enums.json.

export const DestinationType = Object.freeze({
  OWNER: 0,
  CHILD: 1
});
export const PlayAction = Object.freeze({
  PLAY: 0,
  ENQUEUE_PLAY: 1
});
export const ResetBehavior = Object.freeze({
  OBJECT_CENTER: 0,
  LAST_DAMAGELOCATOR_HIT: 1,
  CUSTOM: 2
});
export const StopAction = Object.freeze({
  STOP: 0,
  ENQUEUE_STOP: 1,
  NONE: 2
});
export const Type = Object.freeze({
  FLOAT: 0,
  INTEGER: 1,
  BOOLEAN: 2,
  ENUM: 3
});
export const UnlinkReason = Object.freeze({
  UNLINKING: 0,
  DELETING: 1
});
