// Ported from CarbonEngine (MIT, (c) 2026 CCP Games) - https://github.com/carbonengine/trinity
//   trinity/trinity/Controllers/Tr2TimelineController.h
// Generated by format-carbon carbon-class --emit. Verify against controllers/Tr2TimelineEntry.json.
import { type } from "@carbonenginejs/core-types/schema";
import { CjsModel } from "@carbonenginejs/core-types/model";


/** Tr2TimelineEntry (controllers) - generated from schema shapeHash 542611f6.... */
@type.define({
  className: "Tr2TimelineEntry",
  family: "controllers"
})
export class Tr2TimelineEntry extends CjsModel
{
  /** startTime (float) */
  @type.float32
  startTime = 0;

  /** endTime (float) */
  @type.float32
  endTime = 0;

  /** trackID (uint32_t) */
  @type.uint32
  trackID = 0;
}
