// Ported from CarbonEngine (MIT, (c) 2026 CCP Games) - https://github.com/carbonengine/trinity
//   trinity/trinity/Shader/Tr2EffectDescription.h
// Generated by format-carbon carbon-class --emit. Verify against shader/Tr2SamplerSetup.json.
import { type } from "@carbonenginejs/runtime-utils/schema";
import { CjsModel } from "@carbonenginejs/runtime-utils/model";

/** Tr2SamplerSetup (shader) - generated from schema shapeHash 0d58dc07.... */
@type.define({ className: "Tr2SamplerSetup", family: "shader" })
export class Tr2SamplerSetup extends CjsModel
{

  /** name (const char*) */
  @type.objectRef("char")
  name = null;

  /** sampler (Tr2SamplerStateAL) */
  @type.rawStruct("Tr2SamplerStateAL")
  sampler = null;

}
