// Ported from CarbonEngine (MIT, (c) 2026 CCP Games) - https://github.com/carbonengine/trinity
//   trinity/trinity/Shader/Tr2EffectDescription.h
// Generated by format-carbon carbon-class --emit. Verify against shader/Tr2EffectLibrary.json.
import { type } from "@carbonenginejs/runtime-utils/schema";
import { CjsModel } from "@carbonenginejs/runtime-utils/model";

/** Tr2EffectLibrary (shader) - generated from schema shapeHash fc6addd6.... */
@type.define({ className: "Tr2EffectLibrary", family: "shader" })
export class Tr2EffectLibrary extends CjsModel
{

  /** payloadSize (uint32_t) */
  @type.uint32
  payloadSize = 0;

  /** libraryHandle (uint32_t) */
  @type.uint32
  libraryHandle = 0;

  /** rayGenName (BlueSharedStringW) */
  @type.string
  rayGenName = "";

  /** missName (BlueSharedStringW) */
  @type.string
  missName = "";

  /** closestHitName (BlueSharedStringW) */
  @type.string
  closestHitName = "";

  /** anyHitName (BlueSharedStringW) */
  @type.string
  anyHitName = "";

  /** intersectionName (BlueSharedStringW) */
  @type.string
  intersectionName = "";

  /** hitGroupName (BlueSharedStringW) */
  @type.string
  hitGroupName = "";

  /** globalInput (Tr2EffectStageInput) */
  @type.rawStruct("Tr2EffectStageInput")
  globalInput = null;

  /** localInput (Tr2EffectStageInput) */
  @type.rawStruct("Tr2EffectStageInput")
  localInput = null;

  /** globalResourceSetDesc (Tr2ResourceSetDescriptionAL) */
  @type.rawStruct("Tr2ResourceSetDescriptionAL")
  globalResourceSetDesc = null;

}
