// Ported from CarbonEngine (MIT, (c) 2026 CCP Games) - https://github.com/carbonengine/trinity
//   trinity/trinity/Shader/Tr2EffectDescription.h
// Generated by format-carbon carbon-class --emit. Verify against shader/Tr2EffectResource.json.
import { schema, type } from "@carbonenginejs/core-types/schema";
import { CjsModel } from "@carbonenginejs/core-types/model";

/** Tr2EffectResource (shader) - generated from schema shapeHash 0b6608fc.... */
@type.define({ className: "Tr2EffectResource", family: "shader" })
export class Tr2EffectResource extends CjsModel
{
  static BINDLESS_SAMPLER = 100;

  /** isSRGB (bool) */
  @type.boolean
  isSRGB = false;

  /** isAutoregister (bool) */
  @type.boolean
  isAutoregister = false;

  /** name (const char*) */
  @type.string
  name = "";

  /** type (Type - enum Type) */
  @type.int32
  @schema.enum("Type")
  type = 0;

  /** arrayElements (uint32_t) */
  @type.uint32
  arrayElements = 0;

  static Type = Object.freeze({
    TEXTURE_1D: 1,
    TEXTURE_2D: 2,
    TEXTURE_3D: 3,
    TEXTURE_CUBE: 4,
    TEXTURE_TYPELESS: 5,
    BUFFER: 6,
    STRUCTURED_BUFFER: 7,
    TBUFFER: 8,
    BYTEADDRESS_BUFFER: 9,
    UAV_RWTYPED: 10,
    UAV_RWSTRUCTURED: 11,
    UAV_RWBYTEADDRESS: 12,
    UAV_APPEND_STRUCTURED: 13,
    UAV_CONSUME_STRUCTURED: 14,
    UAV_RWSTRUCTURED_WITH_COUNTER: 15
  });

}
