// Ported from CarbonEngine (MIT, (c) 2026 CCP Games) - https://github.com/carbonengine/trinity
//   trinity/trinity/Shader/Tr2EffectDescription.h
// Generated by format-carbon carbon-class --emit. Verify against shader/Tr2EffectConstant.json.
import { schema, type } from "@carbonenginejs/runtime-utils/schema";
import { CjsModel } from "@carbonenginejs/runtime-utils/model";

/** Tr2EffectConstant (shader) - generated from schema shapeHash a2b58449.... */
@type.define({ className: "Tr2EffectConstant", family: "shader" })
export class Tr2EffectConstant extends CjsModel
{

  /** name (BlueSharedString) */
  @type.string
  name = "";

  /** offset (unsigned) */
  @type.uint32
  offset = 0;

  /** size (unsigned) */
  @type.uint32
  size = 0;

  /** type (Type - enum Type) */
  @type.int32
  @schema.enum("Type")
  type = 0;

  /** dimension (unsigned) */
  @type.uint32
  dimension = 0;

  /** elements (unsigned) */
  @type.uint32
  elements = 0;

  /** isSRGB (bool) */
  @type.boolean
  isSRGB = false;

  /** isAutoregister (bool) */
  @type.boolean
  isAutoregister = false;

  static Type = Object.freeze({
    FLOAT: 0,
    INT: 1,
    UINT: 2,
    BOOL: 3,
    OTHER: 4
  });

}
