// Ported from CarbonEngine (MIT, (c) 2026 CCP Games) - https://github.com/carbonengine/trinity
//   trinity/trinity/Shader/Tr2EffectDescription.h
// Generated by format-carbon carbon-class --emit. Verify against shader/Tr2EffectDefine.json.
import { type } from "@carbonenginejs/core-types/schema";
import { CjsModel } from "@carbonenginejs/core-types/model";

/** Tr2EffectDefine (shader) - generated from schema shapeHash 1697ea36.... */
@type.define({ className: "Tr2EffectDefine", family: "shader" })
export class Tr2EffectDefine extends CjsModel
{

  /** name (const char*) */
  @type.string
  name = "";

  /** value (const char*) */
  @type.string
  value = "";

}
