// Ported from CarbonEngine (MIT, (c) 2026 CCP Games) - https://github.com/carbonengine/trinity
//   trinity/trinity/Shader/Tr2EffectDescription.h
// Generated by format-carbon carbon-class --emit. Verify against shader/Tr2EffectParameterAnnotation.json.
import { schema, type } from "@carbonenginejs/runtime-utils/schema";
import { CjsModel } from "@carbonenginejs/runtime-utils/model";

/** Tr2EffectParameterAnnotation (shader) - generated from schema shapeHash 057c1dbe.... */
@type.define({ className: "Tr2EffectParameterAnnotation", family: "shader" })
export class Tr2EffectParameterAnnotation extends CjsModel
{

  /** name (const char*) */
  @type.string
  name = "";

  /** type (Type - enum Type) */
  @type.int32
  @schema.enum("Type")
  type = 0;

  /** boolValue (bool) */
  @type.boolean
  boolValue = false;

  /** intValue (int) */
  @type.int32
  intValue = 0;

  /** floatValue (float) */
  @type.float32
  floatValue = 0;

  /** stringValue (const char*) */
  @type.string
  stringValue = "";

  static Type = Object.freeze({
    BOOL: 0,
    INT: 1,
    FLOAT: 2,
    STRING: 3
  });

}
