// Ported from CarbonEngine (MIT, (c) 2026 CCP Games) - https://github.com/carbonengine/trinity
//   trinity/trinity/Shader/Tr2EffectDescription.h
// Generated by format-carbon carbon-class --emit. Verify against shader/Tr2EffectStageInput.json.
import { type } from "@carbonenginejs/runtime-utils/schema";
import { CjsModel } from "@carbonenginejs/runtime-utils/model";

/** Tr2EffectStageInput (shader) - generated from schema shapeHash bc7f041a.... */
@type.define({ className: "Tr2EffectStageInput", family: "shader" })
export class Tr2EffectStageInput extends CjsModel
{

  /** m_exists (bool) */
  @type.boolean
  exists = false;

  /** resources (Tr2EffectResourceMap) */
  @type.map("Tr2EffectResource")
  resources = new Map();

  /** uavs (Tr2EffectResourceMap) */
  @type.map("Tr2EffectResource")
  uavs = new Map();

  /** samplers (Tr2SamplerSetupMap) */
  @type.map("Tr2SamplerSetup")
  samplers = new Map();

  /** m_shader (unsigned) */
  @type.uint32
  shader = 0xffffffff;

  /** constants (Tr2EffectConstantVector) */
  @type.list("Tr2EffectConstant")
  constants = [];

  /** m_constantValueSize (unsigned) */
  @type.uint32
  constantValueSize = 0;

  /** constantValues (char[SHADER_CONSTANTS_MAX]) */
  @type.typedArray("Uint8Array")
  constantValues = new Uint8Array(0);

  /** signature (Tr2ShaderSignatureAL) */
  @type.rawStruct("Tr2ShaderSignatureAL")
  signature = null;

  /** annotation (Tr2EffectParameterAnnotationMap) */
  @type.list("Tr2EffectParameterAnnotation")
  annotation = [];

}
