// Ported from CarbonEngine (MIT, (c) 2026 CCP Games) - https://github.com/carbonengine/trinity
//   trinity/trinity/Shader/Tr2EffectDescription.h
// Generated by format-carbon carbon-class --emit. Verify against shader/Tr2EffectDescription.json.
import { type } from "@carbonenginejs/runtime-utils/schema";
import { CjsModel } from "@carbonenginejs/runtime-utils/model";

/** Tr2EffectDescription (shader) - generated from schema shapeHash 67ae7d21.... */
@type.define({ className: "Tr2EffectDescription", family: "shader" })
export class Tr2EffectDescription extends CjsModel
{

  /** techniques (TrackableStdVector<Tr2EffectTechnique>) */
  @type.list("Tr2EffectTechnique")
  techniques = [];

  /** annotations (Tr2EffectAnnotationMap) */
  @type.map("Tr2EffectParameterAnnotationMap")
  annotations = new Map();

}
