// Ported from CarbonEngine (MIT, (c) 2026 CCP Games) - https://github.com/carbonengine/trinity
//   trinity/trinity/Shader/Tr2EffectDescription.h
// Generated by format-carbon carbon-class --emit. Verify against shader/Tr2EffectTechnique.json.
import { type } from "@carbonenginejs/runtime-utils/schema";
import { CjsModel } from "@carbonenginejs/runtime-utils/model";

/** Tr2EffectTechnique (shader) - generated from schema shapeHash c82b7c9f.... */
@type.define({ className: "Tr2EffectTechnique", family: "shader" })
export class Tr2EffectTechnique extends CjsModel
{

  /** name (BlueSharedString) */
  @type.string
  name = "";

  /** passes (TrackableStdVector<Tr2Pass>) */
  @type.list("Tr2Pass")
  passes = [];

  /** libraries (std::vector<Tr2EffectLibrary>) */
  @type.list("Tr2EffectLibrary")
  libraries = [];

  /** shaderTypeMask (unsigned int) */
  @type.uint32
  shaderTypeMask = 0;

}
