// Ported from CarbonEngine (MIT, (c) 2026 CCP Games) - https://github.com/carbonengine/trinity
//   trinity/trinity/Shader/Tr2EffectDescription.h
// Generated by format-carbon carbon-class --emit. Verify against shader/Tr2Pass.json.
import { type } from "@carbonenginejs/runtime-utils/schema";
import { CjsModel } from "@carbonenginejs/runtime-utils/model";

/** Tr2Pass (shader) - generated from schema shapeHash 26164bfc.... */
@type.define({ className: "Tr2Pass", family: "shader" })
export class Tr2Pass extends CjsModel
{

  /** stageInputs (Tr2EffectStageInput) */
  @type.list("Tr2EffectStageInput")
  stageInputs = [];

  /** renderStates (unsigned int) */
  @type.uint32
  renderStates = 0;

  /** shaderTypeMask (unsigned int) */
  @type.uint32
  shaderTypeMask = 0;

  /** shaderProgram (unsigned int) */
  @type.uint32
  shaderProgram = 0;

  /** resourceSetDesc (Tr2ResourceSetDescriptionAL) */
  @type.rawStruct("Tr2ResourceSetDescriptionAL")
  resourceSetDesc = null;

  /** indirectLayout (Tr2IndirectDrawBufferLayout) */
  @type.rawStruct("Tr2IndirectDrawBufferLayout")
  indirectLayout = null;

}
