// Ported from CarbonEngine (MIT, (c) 2026 CCP Games) - https://github.com/carbonengine/trinity
//   trinity/trinity/Shader/Tr2EffectDescription.h
// Generated by format-carbon carbon-class --emit. Verify against shader/Tr2ShaderOption.json.
import { io, type } from "@carbonenginejs/runtime-utils/schema";
import { CjsModel } from "@carbonenginejs/runtime-utils/model";

/** Tr2ShaderOption (shader) - generated from schema shapeHash a79378fe.... */
@type.define({ className: "Tr2ShaderOption", family: "shader" })
export class Tr2ShaderOption extends CjsModel
{

  /** name (BlueSharedString) */
  @io.rebuild("pipeline")
  @io.persist
  @type.string
  name = "";

  /** value (BlueSharedString) */
  @io.rebuild("pipeline")
  @io.persist
  @type.string
  value = "";

}
