// Ported from CarbonEngine (MIT, (c) 2026 CCP Games) - https://github.com/carbonengine/trinity
//   trinity/trinity/Eve/Turret/EveTurretSet.h
// Generated by format-carbon carbon-class --emit. Verify against eve/perObjectData/EveTurretSetPerObjectData.json.
import { type } from "@carbonenginejs/runtime-utils/schema";
import { CjsModel } from "@carbonenginejs/runtime-utils/model";
import { EveTurretSetPSData } from "../attachment/turrets/EveTurretSetPSData.js";
import { EveTurretSetVSData } from "../attachment/turrets/EveTurretSetVSData.js";

/** EveTurretSetPerObjectData (eve/perObjectData) - generated from schema shapeHash e35c9e2a.... */
@type.define({ className: "EveTurretSetPerObjectData", family: "eve/perObjectData" })
export class EveTurretSetPerObjectData extends CjsModel
{

  /** m_vsData (EveTurretSetVSData) */
  @type.rawStruct("EveTurretSetVSData")
  vsData = new EveTurretSetVSData();

  /** m_psData (EveTurretSetPSData) */
  @type.rawStruct("EveTurretSetPSData")
  psData = new EveTurretSetPSData();

}
