// Ported from CarbonEngine (MIT, (c) 2026 CCP Games) - https://github.com/carbonengine/trinity
//   trinity/trinity/Utilities/GeometryUtils.h
// Generated by format-carbon carbon-class --emit. Verify against utilities/AreaBoundsInfo.json.
import { type } from "@carbonenginejs/runtime-utils/schema";
import { CjsModel } from "@carbonenginejs/runtime-utils/model";

/** AreaBoundsInfo (utilities) - generated from schema shapeHash 45ca4425.... */
@type.define({ className: "AreaBoundsInfo", family: "utilities" })
export class AreaBoundsInfo extends CjsModel
{

  /** bounds (BoundingBox) */
  @type.rawStruct("BoundingBox")
  bounds = null;

  /** vertexCount (granny_int32) */
  @type.unknown
  vertexCount = null;

}
