// Ported from CarbonEngine (MIT, (c) 2026 CCP Games) - https://github.com/carbonengine/trinity
//   trinity/trinity/PostProcess/Tr2PostProcessRenderer.h
// Generated by format-carbon carbon-class --emit. Verify against postProcess/CASConstants.json.
import { type } from "@carbonenginejs/core-types/schema";
import { CjsModel } from "@carbonenginejs/core-types/model";

/** CASConstants (postProcess) - generated from schema shapeHash af13b248.... */
@type.define({ className: "CASConstants", family: "postProcess" })
export class CASConstants extends CjsModel
{

  /** const0 (uintfloat4) */
  @type.unknown
  const0 = null;

  /** const1 (uintfloat4) */
  @type.unknown
  const1 = null;

}
