// Ported from CarbonEngine (MIT, (c) 2026 CCP Games) - https://github.com/carbonengine/trinity
//   trinity/trinity/Eve/EveInstancedMeshManager.h
// Generated by format-carbon carbon-class --emit. Verify against eve/scene/EveInstancedMeshManager.json.
import { schema, type } from "@carbonenginejs/runtime-utils/schema";
import { CjsModel } from "@carbonenginejs/runtime-utils/model";
import { vec4 } from "@carbonenginejs/runtime-utils/vec4";

/** EveInstancedMeshManager (eve/scene) - generated from schema shapeHash 167badda.... */
@type.define({ className: "EveInstancedMeshManager", family: "eve/scene" })
export class EveInstancedMeshManager extends CjsModel
{

  /** dynamicInstances (const DynamicPerInstanceData*) */
  @type.objectRef("DynamicPerInstanceData")
  dynamicInstances = null;

  /** owner (IRootPtr) */
  @type.objectRef("IRoot")
  owner = null;

  /** buffer (std::unique_ptr<Tr2BufferAL>) */
  @type.rawStruct("Tr2BufferAL")
  buffer = null;

  /** regions (std::vector<Region>) */
  @type.list("Region")
  regions = [];

  /** retiredBuffers (std::vector<std::unique_ptr<Tr2BufferAL>>) */
  @type.list("Tr2BufferAL")
  retiredBuffers = [];

  /** mappedRetiredBuffers (std::vector<Tr2BufferAL*>) */
  @type.list("Tr2BufferAL")
  mappedRetiredBuffers = [];

  /** meshGroups (std::vector<MeshGroup>) */
  @type.list("MeshGroup")
  meshGroups = [];

  /** currentAllocation (InstanceBuffer::Allocation) */
  @type.rawStruct("InstanceBuffer::Allocation")
  currentAllocation = null;

  /** screenSizeThresholds (std::vector<float>) */
  @type.list("float")
  screenSizeThresholds = [];

  /** flags (InstanceFlags) */
  @type.rawStruct("InstanceFlags")
  flags = null;

  /** screenSizes (std::vector<float>) */
  @type.list("float")
  screenSizes = [];

  /** m_sphereGroups (std::vector<SphereGroup>) */
  @type.list("SphereGroup")
  sphereGroups = [];

  /** m_perObjectDataBuffer (Tr2GpuStructuredBufferPtr) */
  @type.objectRef("Tr2GpuStructuredBuffer")
  perObjectDataBuffer = null;

  /** m_staticInstanceBuffer (InstanceBuffer) */
  @type.rawStruct("InstanceBuffer")
  staticInstanceBuffer = null;

  /** m_dynamicInstanceBuffer (InstanceBuffer) */
  @type.rawStruct("InstanceBuffer")
  dynamicInstanceBuffer = null;

  /** worldTransform (Vector4) */
  @type.vec4
  worldTransform = vec4.create();

  /** prevWorldTransform (Vector4) */
  @type.vec4
  prevWorldTransform = vec4.create();

  /** nullptr (other.owner =) */
  @type.unknown
  nullptr = null;

  /** InvalidIndex (other.index =) */
  @type.unknown
  InvalidIndex = null;

  /** bounds (CcpMath::Sphere) */
  @type.rawStruct("CcpMath::Sphere")
  bounds = null;

  /** radius (float) */
  @type.float32
  radius = 0;

  /** maxScreenSize (float) */
  @type.float32
  maxScreenSize = 0;

  /** perObjectDataIndex (uint32_t) */
  @type.uint32
  perObjectDataIndex = 0;

  /** materialHash (uint64_t) */
  @type.uint64
  materialHash = 0;

  /** meshIndex (uint32_t) */
  @type.uint32
  meshIndex = 0;

  /** areaIndex (uint32_t) */
  @type.uint32
  areaIndex = 0;

  /** count (uint32_t) */
  @type.uint32
  count = 0;

  /** sphereGroupIndex (uint32_t) */
  @type.uint32
  sphereGroupIndex = 0;

  /** ownerIndex (uint32_t) */
  @type.uint32
  ownerIndex = 0;

  /** pickingObjectId (uint32_t) */
  @type.uint32
  pickingObjectId = 0;

  /** offset (uint32_t) */
  @type.uint32
  offset = 0;

  /** length (uint32_t) */
  @type.uint32
  length = 0;

  /** recordedFrame (uint64_t) */
  @type.uint64
  recordedFrame = 0;

  /** totalVisibleInstances (uint32_t) */
  @type.uint32
  totalVisibleInstances = 0;

  /** m_instanceCount (size_t) */
  @type.uint64
  instanceCount = 0;

  /** sphereIndex (uint32_t) */
  @type.uint32
  sphereIndex = 0;

  /** CASTS_SHADOW (static const uint32_t) */
  @type.unknown
  CASTS_SHADOW = null;

  /** RENDER_IN_REFLECTION (static const uint32_t) */
  @type.unknown
  RENDER_IN_REFLECTION = null;

  /** areaCount (uint32_t) */
  @type.uint32
  areaCount = 1;

  /** isDynamic (bool) */
  @type.boolean
  isDynamic = false;

  /** index (uint32_t) */
  @type.uint32
  index = 0;

  /** geometry (TriGeometryRes*) */
  @type.objectRef("TriGeometryRes")
  geometry = null;

  /** handle (MeshGroupHandle*) */
  @type.objectRef("MeshGroupHandle")
  handle = null;

  /** staticInstances (const StaticPerInstanceData*) */
  @type.objectRef("StaticPerInstanceData")
  staticInstances = null;

  /** data (uint8_t*) */
  @type.objectRef("uint8_t")
  data = null;

  /** mappedData (uint8_t*) */
  @type.objectRef("uint8_t")
  mappedData = null;

  /** material (Tr2Effect*) */
  @type.objectRef("Tr2Effect")
  material = null;

  /** boundingSpheres (const CcpMath::Sphere*) */
  @type.objectRef("CcpMath::Sphere")
  boundingSpheres = null;

  /** combinedVertexDeclaration (uint32_t) */
  @type.uint32
  combinedVertexDeclaration = 0;

  /** batchType (TriBatchType - enum TriBatchType) */
  @type.int32
  @schema.enum("TriBatchType")
  batchType = 0;

  /** lastTestResult (TriFrustumTestResult - enum TriFrustumTestResult) */
  @type.int32
  @schema.enum("TriFrustumTestResult")
  lastTestResult = 0;

  static TriBatchType = Object.freeze({
    TRIBATCHTYPE_OPAQUE: 0,
    TRIBATCHTYPE_DECAL: 1,
    TRIBATCHTYPE_TRANSPARENT: 2,
    TRIBATCHTYPE_DEPTH: 3,
    TRIBATCHTYPE_ADDITIVE: 4,
    TRIBATCHTYPE_PICKING: 5,
    TRIBATCHTYPE_MIRROR: 6,
    TRIBATCHTYPE_DECALNORMAL: 7,
    TRIBATCHTYPE_DEPTHNORMAL: 8,
    TRIBATCHTYPE_OPAQUE_PREPASS: 9,
    TRIBATCHTYPE_DECAL_PREPASS: 10,
    TRIBATCHTYPE_GEOMETRY_ERASER: 11,
    TRIBATCHTYPE_FLARE: 12,
    TRIBATCHTYPE_DISTORTION: 13,
    TRIBATCHTYPE_COUNT_OF_BATCH_TYPES: 14,
  });

  static TriFrustumTestResult = Object.freeze({
    Outside: 0,
    Intersect: 1,
    Inside: 2,
  });

}
