// Ported from CarbonEngine (MIT, (c) 2026 CCP Games) - https://github.com/carbonengine/trinity
//   trinity/trinity/Eve/UI/EveSpherePinIndexTree.h
// Generated by format-carbon carbon-class --emit. Verify against eve/ui/EveSpherePinIndexTree.json.
import { type } from "@carbonenginejs/runtime-utils/schema";
import { CjsModel } from "@carbonenginejs/runtime-utils/model";

/** EveSpherePinIndexTree (eve/ui) - generated from schema shapeHash 71effefa.... */
@type.define({ className: "EveSpherePinIndexTree", family: "eve/ui" })
export class EveSpherePinIndexTree extends CjsModel
{

  /** Face (struct) */
  @type.unknown
  Face = null;

  /** TreeNode (struct) */
  @type.unknown
  TreeNode = null;

  /** m_granny (TriGrannyResPtr) */
  @type.objectRef("TriGrannyRes")
  granny = null;

  /** m_tree (TreeNode*) */
  @type.objectRef("TreeNode")
  tree = 0;

  /** m_faces (Face*) */
  @type.objectRef("Face")
  faces = 0;

  /** m_initialized (int) */
  @type.int32
  initialized = 0;

  /** m_markedFaces (std::vector<Face*>) */
  @type.list("Face")
  markedFaces = [];

}
