// Ported from CarbonEngine (MIT, (c) 2026 CCP Games) - https://github.com/carbonengine/trinity
//   trinity/trinity/Include/ITriColor.h
// Generated by format-carbon carbon-class --emit. Verify against include/ITriColor.json.
import { type } from "@carbonenginejs/runtime-utils/schema";
import { CjsModel } from "@carbonenginejs/runtime-utils/model";

/** ITriColor (include) - generated from schema shapeHash 30191a6b.... */
@type.define({ className: "ITriColor", family: "include" })
export class ITriColor extends CjsModel
{

  /** const (::Color * in )) */
  @type.rawStruct("::Color in )")
  const = 0;

}
