// Ported from CarbonEngine (MIT, (c) 2026 CCP Games) - https://github.com/carbonengine/trinity
//   trinity/trinity/Include/ITriEffectParameter.h
// Generated by format-carbon carbon-class --emit. Verify against include/ITriEffectTextureParameter.json.
import { type } from "@carbonenginejs/runtime-utils/schema";
import { CjsModel } from "@carbonenginejs/runtime-utils/model";

/** ITriEffectTextureParameter (include) - generated from schema shapeHash 8e6f7285.... */
@type.define({ className: "ITriEffectTextureParameter", family: "include" })
export class ITriEffectTextureParameter extends CjsModel
{

  /** UV_SET_MAX_COUNT (static const size_t) */
  @type.unknown
  UV_SET_MAX_COUNT = 8;

}
