// Ported from CarbonEngine (MIT, (c) 2026 CCP Games) - https://github.com/carbonengine/trinity
//   trinity/trinity/Include/ITriDevice.h
// Generated by format-carbon carbon-class --emit. Verify against include/ITriDevice.json.
import { type } from "@carbonenginejs/runtime-utils/schema";
import { CjsModel } from "@carbonenginejs/runtime-utils/model";

/** ITriDevice (include) - generated from schema shapeHash 3a872fd8.... */
@type.define({ className: "ITriDevice", family: "include" })
export class ITriDevice extends CjsModel
{

  /** adapter (uint32_t) */
  @type.uint32
  adapter = 0;

}
