// Ported from CarbonEngine (MIT, (c) 2026 CCP Games) - https://github.com/carbonengine/trinity
//   trinity/trinity/Curves/Tr2CurveScalar.h
// Generated by format-carbon carbon-class --emit. Verify against curves/Tr2CurveRasterizeDestination.json.
import { type } from "@carbonenginejs/core-types/schema";
import { CjsModel } from "@carbonenginejs/core-types/model";

/** Tr2CurveRasterizeDestination (curves) - generated from schema shapeHash 8f44878c.... */
@type.define({ className: "Tr2CurveRasterizeDestination", family: "curves" })
export class Tr2CurveRasterizeDestination extends CjsModel
{

  /** width (uint32_t) */
  @type.uint32
  width = 0;

  /** stride (uint32_t) */
  @type.uint32
  stride = 0;

  /** data (Float_16*) */
  @type.objectRef("Float_16")
  data = null;

}
