// Ported from CarbonEngine (MIT, (c) 2026 CCP Games) - https://github.com/carbonengine/trinity
//   trinity/trinity/Curves/Tr2CurveScalar.h
// Generated by format-carbon carbon-class --emit. Verify against curves/Tr2CurveScalarDefinition.json.
import { schema, type } from "@carbonenginejs/core-types/schema";
import { CjsModel } from "@carbonenginejs/core-types/model";

/** Tr2CurveScalarDefinition (curves) - generated from schema shapeHash 09171834.... */
@type.define({ className: "Tr2CurveScalarDefinition", family: "curves" })
export class Tr2CurveScalarDefinition extends CjsModel
{

  /** keys (const Tr2CurveScalarKey*) */
  @type.objectRef("Tr2CurveScalarKey")
  keys = null;

  /** keyCount (uint32_t) */
  @type.uint32
  keyCount = 0;

  /** extrapolationBefore (Tr2CurveExtrapolation::Type - enum Tr2CurveExtrapolation) */
  @type.int32
  @schema.enum("Tr2CurveExtrapolation")
  extrapolationBefore = 0;

  /** extrapolationAfter (Tr2CurveExtrapolation::Type - enum Tr2CurveExtrapolation) */
  @type.int32
  @schema.enum("Tr2CurveExtrapolation")
  extrapolationAfter = 0;

  static Tr2CurveExtrapolation = Object.freeze({
    CLAMP: 0,
    CYCLE: 1,
    MIRROR: 2,
    LINEAR: 3,
  });

}
