// Ported from CarbonEngine (MIT, (c) 2026 CCP Games) - https://github.com/carbonengine/trinity
//   trinity/trinity/Include/Tr2Curve.h
// Generated by format-carbon carbon-class --emit. Verify against curves/Tr2Key.json.
import { schema, type } from "@carbonenginejs/runtime-utils/schema";
import { CjsModel } from "@carbonenginejs/runtime-utils/model";

/** Tr2Key (curves) - generated from schema shapeHash 1a2121bf.... */
@type.define({ className: "Tr2Key", family: "curves" })
export class Tr2Key extends CjsModel
{

  /** m_time (float) */
  @type.float32
  time = 0;

  /** m_value (T) */
  @type.rawStruct("T")
  value = null;

  /** m_interpolation (Interpolation - enum Interpolation) */
  @type.int32
  @schema.enum("Interpolation")
  interpolation = 0;

  static Interpolation = Object.freeze({
    CONSTANT: 0,
    LINEAR: 1,
    HERMITE: 2,
    CATMULLROM: 3,
    SPHERICAL_LINEAR: 4,
    SPHERICAL_QUADRANGLE: 5,
  });

}
