// Ported from CarbonEngine (MIT, (c) 2026 CCP Games) - https://github.com/carbonengine/trinity
//   trinity/trinity/Raytracing/Tr2RaytracingGeometry.h
// Generated by format-carbon carbon-class --emit. Verify against raytracing/Tr2RaytracingMeshArea.json.
import { type } from "@carbonenginejs/core-types/schema";
import { CjsModel } from "@carbonenginejs/core-types/model";

/** Tr2RaytracingMeshArea (raytracing) - generated from schema shapeHash 42a64c2d.... */
@type.define({ className: "Tr2RaytracingMeshArea", family: "raytracing" })
export class Tr2RaytracingMeshArea extends CjsModel
{

  /** m_areaIndex (uint32_t) */
  @type.uint32
  areaIndex = 0;

  /** m_blas (Tr2RtBottomLevelAccelerationStructureAL) */
  @type.rawStruct("Tr2RtBottomLevelAccelerationStructureAL")
  blas = null;

  /** m_blasOutdated (bool) */
  @type.boolean
  blasOutdated = false;

  /** true (m_blasOutdated =) */
  @type.unknown
  true = null;

}
