// Ported from CarbonEngine (MIT, (c) 2026 CCP Games) - https://github.com/carbonengine/trinity
//   trinity/trinity/Include/TriColor.h
// Generated by format-carbon carbon-class --emit. Verify against trinityCore/TriColor.json.
import { carbon, impl, io, type } from "@carbonenginejs/runtime-utils/schema";
import { CjsModel } from "@carbonenginejs/runtime-utils/model";

/** TriColor (trinityCore) - generated from schema shapeHash db7842a1.... */
@type.define({ className: "TriColor", family: "trinityCore" })
export class TriColor extends CjsModel
{

  /** r (unknown) [READWRITE, PERSIST] */
  @io.persist
  @type.unknown
  r = null;

  /** g (unknown) [READWRITE, PERSIST] */
  @io.persist
  @type.unknown
  g = null;

  /** b (unknown) [READWRITE, PERSIST] */
  @io.persist
  @type.unknown
  b = null;

  /** a (float) [READWRITE, PERSIST] */
  @io.persist
  @type.float32
  a = 0;

  /** Carbon method __init__ -> Py__init__ (MAP_METHOD_AND_WRAP_OPTIONAL_ARGS). */
  @carbon.method
  @impl.notImplemented
  __init__(...args)
  {
    throw new Error("TriColor.__init__ is not implemented in CarbonEngineJS.");
  }

  /** Carbon method SetRGB -> PySetRGB (MAP_METHOD_AND_WRAP_OPTIONAL_ARGS). */
  @carbon.method
  @impl.notImplemented
  SetRGB(...args)
  {
    throw new Error("TriColor.SetRGB is not implemented in CarbonEngineJS.");
  }

  /** Carbon method SetHSV -> PySetHSV (MAP_METHOD_AND_WRAP_OPTIONAL_ARGS). */
  @carbon.method
  @impl.notImplemented
  SetHSV(...args)
  {
    throw new Error("TriColor.SetHSV is not implemented in CarbonEngineJS.");
  }

  /** Carbon method SetVector -> PySetVector (MAP_METHOD_AND_WRAP_OPTIONAL_ARGS). */
  @carbon.method
  @impl.notImplemented
  SetVector(...args)
  {
    throw new Error("TriColor.SetVector is not implemented in CarbonEngineJS.");
  }

  /** Carbon method FromInt -> PyFromInt (MAP_METHOD_AND_WRAP). */
  @carbon.method
  @impl.notImplemented
  FromInt(...args)
  {
    throw new Error("TriColor.FromInt is not implemented in CarbonEngineJS.");
  }

  /** Carbon method AsInt -> PyAsInt (MAP_METHOD_AND_WRAP). */
  @carbon.method
  @impl.notImplemented
  AsInt(...args)
  {
    throw new Error("TriColor.AsInt is not implemented in CarbonEngineJS.");
  }

  /** Carbon method GetHSV -> PyGetHSV (MAP_METHOD_AND_WRAP). */
  @carbon.method
  @impl.notImplemented
  GetHSV(...args)
  {
    throw new Error("TriColor.GetHSV is not implemented in CarbonEngineJS.");
  }

  /** Carbon method Scale (MAP_METHOD_AND_WRAP). */
  @carbon.method
  @impl.notImplemented
  Scale(...args)
  {
    throw new Error("TriColor.Scale is not implemented in CarbonEngineJS.");
  }

}
