// Ported from CarbonEngine (MIT, (c) 2026 CCP Games) - https://github.com/carbonengine/trinity
//   trinity/trinity/Include/TriQuaternion.h
// Generated by format-carbon carbon-class --emit. Verify against trinityCore/TriQuaternion.json.
import { carbon, impl, io, type } from "@carbonenginejs/runtime-utils/schema";
import { CjsModel } from "@carbonenginejs/runtime-utils/model";

/** TriQuaternion (trinityCore) - generated from schema shapeHash 3c717b89.... */
@type.define({ className: "TriQuaternion", family: "trinityCore" })
export class TriQuaternion extends CjsModel
{

  /** x (unknown) [READWRITE, PERSIST] */
  @io.persist
  @type.unknown
  x = null;

  /** y (unknown) [READWRITE, PERSIST] */
  @io.persist
  @type.unknown
  y = null;

  /** z (unknown) [READWRITE, PERSIST] */
  @io.persist
  @type.unknown
  z = null;

  /** w (unknown) [READWRITE, PERSIST] */
  @io.persist
  @type.unknown
  w = null;

  /** Carbon method __init__ -> Py__init__ (MAP_METHOD_AND_WRAP_OPTIONAL_ARGS). */
  @carbon.method
  @impl.notImplemented
  __init__(...args)
  {
    throw new Error("TriQuaternion.__init__ is not implemented in CarbonEngineJS.");
  }

  /** Carbon method GetYawPitchRoll -> PyGetYawPitchRoll (MAP_METHOD_AND_WRAP). */
  @carbon.method
  @impl.notImplemented
  GetYawPitchRoll(...args)
  {
    throw new Error("TriQuaternion.GetYawPitchRoll is not implemented in CarbonEngineJS.");
  }

  /** Carbon method Identity -> PyIdentity (MAP_METHOD_AND_WRAP). */
  @carbon.method
  @impl.notImplemented
  Identity(...args)
  {
    throw new Error("TriQuaternion.Identity is not implemented in CarbonEngineJS.");
  }

  /** Carbon method Multiply -> PyMultiply (MAP_METHOD_AND_WRAP). */
  @carbon.method
  @impl.notImplemented
  Multiply(...args)
  {
    throw new Error("TriQuaternion.Multiply is not implemented in CarbonEngineJS.");
  }

  /** Carbon method Normalize -> PyNormalize (MAP_METHOD_AND_WRAP). */
  @carbon.method
  @impl.notImplemented
  Normalize(...args)
  {
    throw new Error("TriQuaternion.Normalize is not implemented in CarbonEngineJS.");
  }

  /** Carbon method Length -> PyLength (MAP_METHOD_AND_WRAP). */
  @carbon.method
  @impl.notImplemented
  Length(...args)
  {
    throw new Error("TriQuaternion.Length is not implemented in CarbonEngineJS.");
  }

  /** Carbon method Scale -> PyScale (MAP_METHOD_AND_WRAP). */
  @carbon.method
  @impl.notImplemented
  Scale(...args)
  {
    throw new Error("TriQuaternion.Scale is not implemented in CarbonEngineJS.");
  }

  /** Carbon method SetRotationAxis -> PySetRotationAxis (MAP_METHOD_AND_WRAP). */
  @carbon.method
  @impl.notImplemented
  SetRotationAxis(...args)
  {
    throw new Error("TriQuaternion.SetRotationAxis is not implemented in CarbonEngineJS.");
  }

  /** Carbon method RotationAxis -> PyRotationAxis (MAP_METHOD_AND_WRAP). */
  @carbon.method
  @impl.notImplemented
  RotationAxis(...args)
  {
    throw new Error("TriQuaternion.RotationAxis is not implemented in CarbonEngineJS.");
  }

  /** Carbon method SetYawPitchRoll (MAP_METHOD_AND_WRAP). */
  @carbon.method
  @impl.notImplemented
  SetYawPitchRoll(...args)
  {
    throw new Error("TriQuaternion.SetYawPitchRoll is not implemented in CarbonEngineJS.");
  }

  /** Carbon method SetIdentity (MAP_METHOD_AND_WRAP). */
  @carbon.method
  @impl.notImplemented
  SetIdentity(...args)
  {
    throw new Error("TriQuaternion.SetIdentity is not implemented in CarbonEngineJS.");
  }

  /** Carbon method SetXYZW (MAP_METHOD_AND_WRAP). */
  @carbon.method
  @impl.notImplemented
  SetXYZW(...args)
  {
    throw new Error("TriQuaternion.SetXYZW is not implemented in CarbonEngineJS.");
  }

}
