// Ported from CarbonEngine (MIT, (c) 2026 CCP Games) - https://github.com/carbonengine/trinity
//   trinity/trinity/Utilities/Vector4d.h
// Generated by format-carbon carbon-class --emit. Verify against utilities/Vector4d.json.
import { type } from "@carbonenginejs/runtime-utils/schema";
import { CjsModel } from "@carbonenginejs/runtime-utils/model";

/** Vector4d (utilities) - generated from schema shapeHash 733e0427.... */
@type.define({ className: "Vector4d", family: "utilities" })
export class Vector4d extends CjsModel
{

  /** d (x *=) */
  @type.unknown
  d = null;

  /** dDiv (x *=) */
  @type.unknown
  dDiv = null;

  /** x (double) */
  @type.float64
  x = 0;

  /** y (double) */
  @type.float64
  y = 0;

  /** z (double) */
  @type.float64
  z = 0;

  /** w (double) */
  @type.float64
  w = 0;

  /** f (x =) */
  @type.unknown
  f = null;

}
