// Ported from CarbonEngine (MIT, (c) 2026 CCP Games) - https://github.com/carbonengine/trinity
// Maintained as runtime-trinity's backend-neutral turret constant-data contract.
//   trinity/trinity/Eve/Turret/EveTurretSet.h
// Generated by format-carbon carbon-class --emit. Verify against eve/attachment/turrets/EveTurretSetPSData.json.
import { type } from "@carbonenginejs/core-types/schema";
import { CjsModel } from "@carbonenginejs/core-types/model";
import { vec3 } from "@carbonenginejs/core-math/vec3";
import { vec4 } from "@carbonenginejs/core-math/vec4";

/** EveTurretSetPSData (eve/attachment/turrets) - generated from schema shapeHash 564e83a6.... */
@type.define({ className: "EveTurretSetPSData", family: "eve/attachment/turrets" })
export class EveTurretSetPSData extends CjsModel
{

  /** m_shipData (Vector4) */
  @type.vec4
  shipData = vec4.create();

  /** m_clipData1 (Vector4) */
  @type.vec4
  clipData1 = vec4.create();

  /** m_clipRadius2Sq (float) */
  @type.float32
  clipRadius2Sq = 0;

  /** m_unused (Vector3) */
  @type.vec3
  unused = vec3.create();

  /** m_shLightingCoefficients (Vector4[7]) */
  @type.rawStruct("Vector4[7]")
  shLightingCoefficients = Array.from({ length: 7 }, () => vec4.create());

}
