// Ported from CarbonEngine (MIT, (c) 2026 CCP Games) - https://github.com/carbonengine/trinity
//   trinity/trinity/Eve/Turret/EveTurretSet.h
// Generated by format-carbon carbon-class --emit. Verify against eve/attachment/turrets/EveTurretSet.json.
import { carbon, impl, io, schema, type } from "@carbonenginejs/core-types/schema";
import { EveEntity } from "../../../generated/eve/EveEntity.js";
import { EveTurretTarget } from "./EveTurretTarget.js";
import { mat4 } from "@carbonenginejs/core-math/mat4";
import { quat } from "@carbonenginejs/core-math/quat";
import { vec3 } from "@carbonenginejs/core-math/vec3";
import { vec4 } from "@carbonenginejs/core-math/vec4";

/** EveTurretSet (eve/attachment/turrets) - generated from schema shapeHash 51c12edb.... */
@type.define({ className: "EveTurretSet", family: "eve/attachment/turrets" })
export class EveTurretSet extends EveEntity
{

  /** m_impactBehaviour (ImpactBehaviour::Type - enum ImpactBehaviour) [READWRITE, NOTIFY, PERSIST, ENUM] */
  @io.notify
  @io.persist
  @type.int32
  @schema.enum("ImpactBehaviour")
  impactBehaviour = 0;

  /** m_firingEffect (EveTurretFiringFXPtr) [HIDDEN] */
  @type.objectRef("EveTurretFiringFX")
  firingEffect = null;

  /** m_ambientEffect (IEveSpaceObjectChildPtr) [PERSISTONLY] */
  @io.persistOnly
  @type.model("IEveSpaceObjectChild")
  ambientEffect = null;

  /** m_name (std::string) [READWRITE, PERSIST] */
  @io.persist
  @type.string
  name = "";

  /** m_firingEffectResPath (std::string) [READWRITE, PERSIST] */
  @io.persist
  @type.string
  firingEffectResPath = "";

  /** m_chooseRandomLocator (bool) [READWRITE, PERSIST] */
  @io.persist
  @type.boolean
  chooseRandomLocator = true;

  /** m_boundingSphere (Vector4) [READWRITE, PERSIST] */
  @io.persist
  @type.vec4
  boundingSphere = vec4.create();

  /** m_randomizeExplosionRotation (bool) [READWRITE, PERSIST] */
  @io.persist
  @type.boolean
  randomizeExplosionRotation = true;

  /** m_lodLevel (LOD - enum LOD) [READ] */
  @io.read
  @type.int32
  @schema.enum("LOD")
  lodLevel = 0;

  /** m_currentCyclingFiresPos (uint32_t) [READ] */
  @io.read
  @type.uint32
  currentCyclingFiresPos = 0;

  /** m_useRandomFiringDelay (bool) [READWRITE, PERSIST] */
  @io.persist
  @type.boolean
  useRandomFiringDelay = true;

  /** m_bottomClipHeight (float) [READWRITE, PERSIST] */
  @io.persist
  @type.float32
  bottomClipHeight = 0;

  /** m_geometryResource (TriGeometryResPtr) [READ] */
  @io.read
  @type.objectRef("TriGeometryRes")
  geometryResource = null;

  /** m_maxTrackingTime (float) [READWRITE, PERSIST] */
  @io.persist
  @type.float32
  maxTrackingTime = 1;

  /** m_visibleCount (unsigned int) [READ] */
  @io.read
  @type.uint32
  visibleCount = 0;

  /** m_trackingInfluence (float) [READ] */
  @io.read
  @type.float32
  trackingInfluence = 0;

  /** m_swarmID (unsigned int) [READWRITE] */
  @io.readwrite
  @type.uint32
  swarmID = 0;

  /** m_maxCyclingFirePos (uint32_t) [READWRITE, PERSIST] */
  @io.persist
  @type.uint32
  maxCyclingFirePos = 1;

  /** m_playMovementSound (bool) [READWRITE, PERSIST] */
  @io.persist
  @type.boolean
  playMovementSound = true;

  /** m_isOnline (bool) [READWRITE] */
  @io.readwrite
  @type.boolean
  isOnline = true;

  /** m_target (EveTurretTargetPtr) [READ] */
  @io.read
  @type.objectRef("EveTurretTarget")
  target = new EveTurretTarget();

  /** m_locatorName (std::string) [READWRITE, PERSIST] */
  @io.persist
  @type.string
  locatorName = "";

  /** m_sysBonePitchFactor (float) [READWRITE, PERSIST] */
  @io.persist
  @type.float32
  sysBonePitchFactor = 1;

  /** m_sysBonePitchMax (float) [READWRITE, PERSIST] */
  @io.persist
  @type.float32
  sysBonePitchMax = 90;

  /** m_sysBonePitchMin (float) [READWRITE, PERSIST] */
  @io.persist
  @type.float32
  sysBonePitchMin = 0;

  /** m_sysBonePitchOffset (float) [READWRITE, PERSIST] */
  @io.persist
  @type.float32
  sysBonePitchOffset = 0;

  /** m_sysBonePitch01Factor (float) [READWRITE, PERSIST] */
  @io.persist
  @type.float32
  sysBonePitch01Factor = 1;

  /** m_sysBonePitch01Offset (float) [READWRITE, PERSIST] */
  @io.persist
  @type.float32
  sysBonePitch01Offset = 0;

  /** m_sysBonePitch02Factor (float) [READWRITE, PERSIST] */
  @io.persist
  @type.float32
  sysBonePitch02Factor = 1;

  /** m_sysBonePitch02Offset (float) [READWRITE, PERSIST] */
  @io.persist
  @type.float32
  sysBonePitch02Offset = 0;

  /** m_sysBonePitch03Factor (float) [READWRITE, PERSIST] */
  @io.persist
  @type.float32
  sysBonePitch03Factor = 1;

  /** m_sysBonePitch03Offset (float) [READWRITE, PERSIST] */
  @io.persist
  @type.float32
  sysBonePitch03Offset = 0;

  /** m_updatePitchPose (bool) [READWRITE, PERSIST] */
  @io.persist
  @type.boolean
  updatePitchPose = false;

  /** m_geomResPath (std::string) [READWRITE, NOTIFY, PERSIST] */
  @io.notify
  @io.persist
  @type.string
  geometryResPath = "";

  /** m_impactSize (float) [READWRITE, PERSIST] */
  @io.persist
  @type.float32
  impactSize = 0;

  /** m_state (State - enum State) [READ, PERSIST] */
  @io.persist
  @type.int32
  @schema.enum("State")
  state = 2;

  /** m_sysBoneHeight (float) [READWRITE, PERSIST] */
  @io.persist
  @type.float32
  sysBoneHeight = 1;

  /** m_randomFiringDelay (float) [READ] */
  @io.read
  @type.float32
  randomFiringDelay = 0;

  /** m_turretEffect (Tr2EffectPtr) [READWRITE, PERSIST] */
  @io.persist
  @type.model("Tr2Effect")
  turretEffect = null;

  /** m_idleToTargetingMovementAudioEvent (std::wstring) [READWRITE, PERSIST] */
  @io.persist
  @type.string
  idleToTargetingMovementAudioEvent = "";

  /** m_targetingToIdleMovementAudioEvent (std::wstring) [READWRITE, PERSIST] */
  @io.persist
  @type.string
  targetingToIdleMovementAudioEvent = "";

  /** m_generatedDistributedAmbientEffect (EveChildInstanceContainerPtr) [READ] */
  @io.read
  @type.objectRef("EveChildInstanceContainer")
  generatedDistributedAmbientEffect = null;

  /** m_cyclingFireGroupCount (uint32_t) [READWRITE, PERSIST] */
  @io.persist
  @type.uint32
  cyclingFireGroupCount = 1;

  /** m_turretMovementObserver (TriObserverLocalPtr) [READWRITE, PERSIST] */
  @io.persist
  @type.model("TriObserverLocal")
  turretMovementObserver = null;

  /** m_slotNumber (int) [READWRITE] */
  @io.readwrite
  @type.int32
  slotNumber = -1;

  /** m_ambientEffectEditingMode (bool) [READWRITE, NOTIFY] */
  @io.notify
  @io.readwrite
  @type.boolean
  ambientEffectEditingMode = false;

  /** m_displayEffects (bool) [READWRITE] */
  @io.readwrite
  @type.boolean
  displayEffects = true;

  /** m_display (bool) [READWRITE] */
  @io.readwrite
  @type.boolean
  display = true;

  /** m_useDynamicBounds (bool) [READWRITE, PERSIST, NOTIFY] */
  @io.notify
  @io.persist
  @type.boolean
  useDynamicBounds = false;

  /** m_estimatedPixelDiameter (float) [READ] */
  @io.read
  @type.float32
  estimatedPixelDiameter = -1;

  /** m_lowLodFiringEffectScale (Vector3) [READWRITE, PERSIST] */
  @io.persist
  @type.vec3
  lowLodFiringEffectScale = vec3.fromValues(1, 1, 1);

  /** m_lowLodFiringEffectTranslation (Vector3) [READWRITE, PERSIST] */
  @io.persist
  @type.vec3
  lowLodFiringEffectTranslation = vec3.create();

  /** m_lowLodFiringEffectRotation (Quaternion) [READWRITE, PERSIST] */
  @io.persist
  @type.quat
  lowLodFiringEffectRotation = quat.create();

  /** m_useLowLodFiringTransform (bool) [READWRITE, PERSIST] */
  @io.persist
  @type.boolean
  useLowLodFiringTransform = false;

  /** m_laserMissBehaviour (bool) [READWRITE, PERSIST] */
  @io.persist
  @type.boolean
  laserMissBehaviour = false;

  /** m_projectileMissBehaviour (bool) [READWRITE, PERSIST] */
  @io.persist
  @type.boolean
  projectileMissBehaviour = false;

  #turrets = [];

  #parentTransform = mat4.create();

  #activeTurret = EveTurretSet.INVALID_INDEX;

  #highDetailFrozen = false;

  #trackingInfluenceDelta = 0;

  #delayToFadeOutTracking = 0;

  #delayToFadeInTracking = 0;

  #recheckTimeLeft = 2;

  /** Carbon method RebuildBoundingSphere (MAP_METHOD_AND_WRAP). */
  @carbon.method
  @impl.adapted
  @impl.reason("Geometry resources are duck-typed; runtime-trinity stores their computed sphere without realizing render buffers.")
  RebuildBoundingSphere()
  {
    const resource = this.geometryResource;
    if (!resource) return false;
    resource.RecalculateBoundingSphere?.();
    const value = resource.GetBoundingSphere?.(0, this.boundingSphere);
    if (value?.length >= 4 && value !== this.boundingSphere) vec4.copy(this.boundingSphere, value);
    return value !== false;
  }

  /** Carbon method ForceStateDeactive (MAP_METHOD_AND_WRAP). */
  @carbon.method
  @impl.adapted
  @impl.reason("Animation calls are forwarded to hydrated turret/controller objects without Carbon's Granny controller.")
  ForceStateDeactive()
  {
    this.trackingInfluence = 0;
    this.#delayToFadeOutTracking = 0;
    this.#activeTurret = EveTurretSet.INVALID_INDEX;
    this.target?.StopFireAtLocator?.();
    this.firingEffect?.StopFiring?.();
    this.state = EveTurretSet.State.STATE_DEACTIVE;
    this.#playAll("", "Inactive", 0);
    this.#setAmbientState();
  }

  /** Carbon method ForceStateTargeting (MAP_METHOD_AND_WRAP). */
  @carbon.method
  @impl.adapted
  @impl.reason("Animation calls are forwarded to hydrated turret/controller objects without Carbon's Granny controller.")
  ForceStateTargeting()
  {
    this.trackingInfluence = this.maxTrackingTime;
    this.#trackingInfluenceDelta = 0;
    this.#activeTurret = this.GetClosestTurret();
    this.state = EveTurretSet.State.STATE_TARGETING;
    this.#playTurret(this.#activeTurret, "", "Active", 0);
    this.#setAmbientState();
  }

  /** Carbon method FreezeHighDetailLOD (MAP_METHOD_AND_WRAP). */
  @carbon.method
  @impl.adapted
  @impl.reason("The graph freezes its LOD state; geometry realization remains a runtime-engine responsibility.")
  FreezeHighDetailLOD()
  {
    this.lodLevel = EveTurretSet.LOD.LOD_DISABLED;
    this.#highDetailFrozen = true;
    this.geometryResource?.Prepare?.();
  }

  /** Carbon method GetShotTimeVariance (MAP_METHOD_AND_WRAP). */
  @carbon.method
  @impl.implemented
  GetShotTimeVariance()
  {
    return 0.6;
  }

  /** Carbon method MissQueueSize (MAP_METHOD_AND_WRAP). */
  @carbon.method
  @impl.implemented
  MissQueueSize()
  {
    return this.target?.MissQueueSize?.() ?? 0;
  }

  /** Carbon method GetLastShotTime (MAP_METHOD_AND_WRAP). */
  @carbon.method
  @impl.implemented
  GetLastShotTime()
  {
    return this.target?.GetLastShotTime?.() ?? 0;
  }

  /** Carbon method EnterStateDeactive (MAP_METHOD_AND_WRAP). */
  @carbon.method
  @impl.adapted
  @impl.reason("Animation calls are forwarded to hydrated turret/controller objects without Carbon's Granny controller.")
  EnterStateDeactive()
  {
    if (this.state === EveTurretSet.State.STATE_DEACTIVE) return;
    if (this.state === EveTurretSet.State.STATE_FIRING) this.firingEffect?.StopFiring?.();
    if (this.state === EveTurretSet.State.STATE_TARGETING || this.state === EveTurretSet.State.STATE_FIRING)
    {
      this.#delayToFadeOutTracking = 0.0001;
      this.#activeTurret = EveTurretSet.INVALID_INDEX;
      this.target?.StopFireAtLocator?.();
      this.#playAll("Pack", "Inactive", 1);
    }
    else
    {
      this.trackingInfluence = 0;
      this.#delayToFadeOutTracking = 0;
      this.#playAll("Pack", "Inactive", 0);
    }
    this.state = EveTurretSet.State.STATE_DEACTIVE;
    this.#setAmbientState();
  }

  /** Carbon method EnterStateFiring (MAP_METHOD_AND_WRAP). */
  @carbon.method
  @impl.adapted
  @impl.reason("Carbon's geometry/animation selection is represented by portable turret records and controller forwarding.")
  EnterStateFiring()
  {
    if (!this.#setupFiringState()) return false;
    if (this.firingEffect && this.state === EveTurretSet.State.STATE_FIRING)
    {
      if (this.firingEffect.IsLooping?.())
      {
        this.firingEffect.PrepareFiringEffectMoveObjects?.();
        return true;
      }
      this.firingEffect.StopFiring?.();
    }
    if (this.firingEffect)
    {
      if (this.maxCyclingFirePos > 1) this.firingEffect.PrepareFiring?.(this.randomFiringDelay, this.currentCyclingFiresPos, this.cyclingFireGroupCount);
      else this.firingEffect.PrepareFiring?.(this.randomFiringDelay);
      this.firingEffect.SetImpactConfiguration?.(this.target?.GetImpactConfiguration?.());
    }
    this.state = EveTurretSet.State.STATE_FIRING;
    this.#setAmbientState();
    return true;
  }

  /** Carbon method EnterStateIdle (MAP_METHOD_AND_WRAP). */
  @carbon.method
  @impl.adapted
  @impl.reason("Animation calls are forwarded to hydrated turret/controller objects without Carbon's Granny controller.")
  EnterStateIdle()
  {
    if (!this.isOnline) return;
    if (this.state === EveTurretSet.State.STATE_DEACTIVE)
    {
      this.#playAll("Deploy", "Active", 0);
      this.trackingInfluence = 0;
    }
    else if (this.state === EveTurretSet.State.STATE_TARGETING || this.state === EveTurretSet.State.STATE_FIRING)
    {
      this.#delayToFadeOutTracking = 0.0001;
      this.#activeTurret = EveTurretSet.INVALID_INDEX;
      this.target?.StopFireAtLocator?.();
      this.firingEffect?.StopFiring?.();
      this.#playAll("", "Active", 1);
      this.turretMovementObserver?.GetObserver?.()?.SendEvent?.(this.targetingToIdleMovementAudioEvent);
    }
    else this.#playAll("", "Active", 0);
    this.state = EveTurretSet.State.STATE_IDLE;
    this.#setAmbientState();
  }

  /** Carbon method EnterStateReloading (MAP_METHOD_AND_WRAP). */
  @carbon.method
  @impl.adapted
  @impl.reason("Animation calls are forwarded to hydrated turret/controller objects without Carbon's Granny controller.")
  EnterStateReloading()
  {
    const wasDeactive = this.state === EveTurretSet.State.STATE_DEACTIVE;
    if (this.state === EveTurretSet.State.STATE_TARGETING || this.state === EveTurretSet.State.STATE_FIRING)
    {
      this.#delayToFadeOutTracking = 0.0001;
      this.#activeTurret = EveTurretSet.INVALID_INDEX;
      this.target?.StopFireAtLocator?.();
      this.firingEffect?.StopFiring?.();
      this.#playAll("Reload", "Active", 1);
    }
    else if (!wasDeactive) this.#playAll("Reload", "Active", 0);
    this.state = EveTurretSet.State.STATE_RELOADING;
    this.#setAmbientState();
  }

  /** Carbon method EnterStateTargeting (MAP_METHOD_AND_WRAP). */
  @carbon.method
  @impl.adapted
  @impl.reason("Animation calls are forwarded to hydrated turret/controller objects without Carbon's Granny controller.")
  EnterStateTargeting()
  {
    if (!this.isOnline) return;
    if (this.state === EveTurretSet.State.STATE_DEACTIVE)
    {
      this.#delayToFadeInTracking = this.#playAll("Deploy", "Active", 1) + 0.0001;
    }
    else if (this.state === EveTurretSet.State.STATE_IDLE || this.state === EveTurretSet.State.STATE_RELOADING)
    {
      this.#delayToFadeInTracking = 0.0001;
      this.#playAll("", "Active", 1);
    }
    else if (this.state === EveTurretSet.State.STATE_FIRING)
    {
      this.#activeTurret = EveTurretSet.INVALID_INDEX;
      this.target?.StopFireAtLocator?.();
      this.firingEffect?.StopFiring?.();
      this.#playAll("", "Active", 0);
    }
    this.state = EveTurretSet.State.STATE_TARGETING;
    this.#setAmbientState();
  }

  /** Carbon method HandleControllerEvent (MAP_METHOD_AND_WRAP). */
  @carbon.method
  @impl.adapted
  @impl.reason("Controller ownership is represented by direct firing/ambient child forwarding.")
  HandleControllerEvent(name)
  {
    this.firingEffect?.HandleControllerEvent?.(name);
    this.#ambientEffect()?.HandleControllerEvent?.(name);
  }

  /** Carbon method GetFiringBoneWorldTransform (MAP_METHOD_AND_WRAP). */
  @carbon.method
  @impl.adapted
  @impl.reason("Portable turret records and duck-typed geometry bone transforms replace Carbon's CMF/Granny split.")
  GetFiringBoneWorldTransform(muzzle = 0, out = mat4.create())
  {
    let turretIndex = this.#activeTurret;
    if (turretIndex === EveTurretSet.INVALID_INDEX) turretIndex = this.GetClosestTurret();
    if (turretIndex === EveTurretSet.INVALID_INDEX) return mat4.copy(out, this.#parentTransform);
    const turret = this.#turrets[turretIndex];
    const world = turret?.worldMatrix ?? turret?.transform ?? turret;
    if (world?.length === 16) mat4.copy(out, world);
    else mat4.copy(out, this.#parentTransform);
    if (!this.firingEffect) return out;
    const boneID = this.firingEffect?.GetPerMuzzleBoneID?.(muzzle) ?? EveTurretSet.INVALID_INDEX;
    if (boneID === EveTurretSet.INVALID_INDEX)
    {
      if (this.useLowLodFiringTransform)
      {
        mat4.fromRotationTranslationScale(EveTurretSet.#lowLodTransform, this.lowLodFiringEffectRotation, this.lowLodFiringEffectTranslation, this.lowLodFiringEffectScale);
        mat4.multiply(out, out, EveTurretSet.#lowLodTransform);
      }
      return out;
    }
    const boneTransform = turret?.GetBoneTransform?.(boneID, EveTurretSet.#boneTransform)
      ?? this.geometryResource?.GetBoneTransform?.(turretIndex, boneID, EveTurretSet.#boneTransform);
    if (boneTransform?.length === 16)
    {
      if (boneTransform !== EveTurretSet.#boneTransform) mat4.copy(EveTurretSet.#boneTransform, boneTransform);
      return mat4.multiply(out, out, EveTurretSet.#boneTransform);
    }
    if (this.useLowLodFiringTransform)
    {
      mat4.fromRotationTranslationScale(EveTurretSet.#lowLodTransform, this.lowLodFiringEffectRotation, this.lowLodFiringEffectTranslation, this.lowLodFiringEffectScale);
      mat4.multiply(out, out, EveTurretSet.#lowLodTransform);
      return out;
    }
    if (this.sysBonePitchMin < 45)
    {
      vec3.set(EveTurretSet.#turretPosition, out[12], out[13], out[14]);
      const target = this.target?.GetTrackingPosition?.() ?? this.target?.position ?? EveTurretSet.#zero;
      vec3.subtract(EveTurretSet.#targetDirection, target, EveTurretSet.#turretPosition);
      if (vec3.squaredLength(EveTurretSet.#targetDirection))
      {
        quat.rotationTo(EveTurretSet.#directRotation, EveTurretSet.#unitZ, EveTurretSet.#targetDirection);
        mat4.fromRotationTranslation(out, EveTurretSet.#directRotation, EveTurretSet.#turretPosition);
      }
    }
    else
    {
      mat4.fromXRotation(EveTurretSet.#launcherRotation, -Math.PI * 0.5);
      mat4.multiply(out, out, EveTurretSet.#launcherRotation);
    }
    return out;
  }

  /** Carbon method SetControllerVariable (MAP_METHOD_AND_WRAP). */
  @carbon.method
  @impl.adapted
  @impl.reason("Controller ownership is represented by direct firing/ambient child forwarding.")
  SetControllerVariable(name, value)
  {
    this.firingEffect?.SetControllerVariable?.(name, value);
    this.#ambientEffect()?.SetControllerVariable?.(name, value);
  }

  /** Carbon method SetShotMissed (MAP_METHOD_AND_WRAP). */
  @carbon.method
  @impl.implemented
  SetShotMissed(missed)
  {
    this.target?.SetShotMissed?.(missed);
  }

  /** Carbon method StartControllers (MAP_METHOD_AND_WRAP). */
  @carbon.method
  @impl.adapted
  @impl.reason("Controller ownership is represented by direct firing/ambient child forwarding.")
  StartControllers()
  {
    this.firingEffect?.StartControllers?.();
    this.#ambientEffect()?.StartControllers?.();
  }

  @carbon.method
  @impl.adapted
  @impl.reason("Resource loading and GPU preparation are engine responsibilities; Trinity initializes the target and owned behavior graph.")
  Initialize()
  {
    this.target ??= new EveTurretTarget();
    this.target.SetBehaviour?.(this.laserMissBehaviour, this.projectileMissBehaviour, this.impactSize, this.impactBehaviour);
    this.firingEffect?.Initialize?.();
    this.#ambientEffect()?.Initialize?.();
    return true;
  }

  @carbon.method
  @impl.implemented
  SetFiringEffect(effect)
  {
    this.firingEffect = effect ?? null;
    this.firingEffect?.Initialize?.();
  }

  @carbon.method
  @impl.adapted
  @impl.reason("Carbon QueryInterface target attachment is delegated to EveTurretTarget's browser-compatible target validation.")
  SetTargetObject(object)
  {
    this.target ??= new EveTurretTarget();
    const previous = this.target.GetTargetable?.();
    const accepted = this.target.SetTargetable(object);
    if (accepted)
    {
      if ((this.state === EveTurretSet.State.STATE_IDLE || previous !== object) && this.playMovementSound && this.idleToTargetingMovementAudioEvent)
      {
        this.turretMovementObserver?.GetObserver?.()?.SendEvent?.(this.idleToTargetingMovementAudioEvent);
      }
      this.SetTargetScale();
    }
    return accepted;
  }

  @carbon.method
  @impl.implemented
  GetTargetObject()
  {
    return this.target?.GetTargetable?.() ?? null;
  }

  @carbon.method
  @impl.implemented
  SetTargetScale()
  {
    this.firingEffect?.SetScaleByRadius?.(this.target?.GetRadius?.() ?? -1);
  }

  @carbon.method
  @impl.adapted
  @impl.reason("Carbon builds hidden SingleTurret records from geometry locators; browser hosts may provide equivalent portable records directly.")
  SetTurrets(turrets = [])
  {
    this.#turrets = Array.from(turrets).slice(0, EveTurretSet.MAX_TURRETS_PER_SET).map(turret => this.#normalizeTurret(turret));
    this.visibleCount = this.#turrets.length;
    return this.#turrets;
  }

  @carbon.method
  @impl.adapted
  @impl.reason("Carbon builds hidden SingleTurret records from geometry locators; browser hosts may provide equivalent portable records directly.")
  AddTurret(turret)
  {
    if (this.#turrets.length >= EveTurretSet.MAX_TURRETS_PER_SET) return null;
    const value = this.#normalizeTurret(turret);
    this.#turrets.push(value);
    this.visibleCount = this.#turrets.length;
    return value;
  }

  @carbon.method
  @impl.implemented
  GetTurrets()
  {
    return this.#turrets;
  }

  /** Carbon method SetLocalTransform. */
  @carbon.method
  @impl.adapted
  @impl.reason("Portable records replace Carbon's CMF/Granny SingleTurretData allocation while retaining its fixed 24-turret limit and scale removal.")
  SetLocalTransform(turretIndex, localMatrix)
  {
    const index = Number(turretIndex) >>> 0;
    if (index >= EveTurretSet.MAX_TURRETS_PER_SET || localMatrix?.length !== 16) return false;
    while (this.#turrets.length <= index)
    {
      const turret = this.#normalizeTurret(null);
      turret.valid = false;
      turret.display = false;
      this.#turrets.push(turret);
    }
    const turret = this.#turrets[index];
    mat4.getRotation(EveTurretSet.#localRotation, localMatrix);
    mat4.getTranslation(EveTurretSet.#localTranslation, localMatrix);
    mat4.fromRotationTranslation(turret.localMatrix, EveTurretSet.#localRotation, EveTurretSet.#localTranslation);
    quat.copy(turret.localQuaternion, EveTurretSet.#localRotation);
    vec4.set(turret.localPosition, EveTurretSet.#localTranslation[0], EveTurretSet.#localTranslation[1], EveTurretSet.#localTranslation[2], 1);
    turret.valid = false;
    turret.display = false;
    this.generatedDistributedAmbientEffect?.UpdateInstance?.(index, EveTurretSet.#unitScale, turret.localQuaternion, EveTurretSet.#localTranslation);
    this.visibleCount = this.#turrets.length;
    return true;
  }

  @carbon.method
  @impl.implemented
  SetParentTransform(transform)
  {
    mat4.copy(this.#parentTransform, transform);
    this.UpdateTurretTransforms(transform);
  }

  @carbon.method
  @impl.implemented
  UpdateTurretTransforms(parentTransform = this.#parentTransform)
  {
    mat4.copy(this.#parentTransform, parentTransform);
    for (const turret of this.#turrets)
    {
      mat4.multiply(turret.worldMatrix, parentTransform, turret.localMatrix);
      turret.valid = true;
    }
  }

  @carbon.method
  @impl.adapted
  @impl.reason("The closest portable turret is selected from its world up-axis and the target tracking position.")
  GetClosestTurret()
  {
    return this.#getClosestTurretAndLocator().turret;
  }

  @carbon.method
  @impl.adapted
  @impl.reason("This combined browser convenience update runs Carbon's explicit synchronous and asynchronous phases in order.")
  Update(context)
  {
    this.UpdateSyncronous(context);
    this.UpdateAsyncronous(context, this.#parentTransform);
    return true;
  }

  @carbon.method
  @impl.adapted
  @impl.reason("Animation cleanup and task dispatch are forwarded through portable records; target and firing timing remain source-faithful.")
  UpdateSyncronous(context, parentTransform = this.#parentTransform)
  {
    const deltaTime = Number(context?.GetDeltaT?.() ?? context?.deltaTime ?? context?.deltaT ?? 0);
    if (parentTransform?.length === 16) mat4.copy(this.#parentTransform, parentTransform);
    if (this.firingEffect)
    {
      if (this.#activeTurret !== EveTurretSet.INVALID_INDEX && this.firingEffect.IsLooping?.() && this.state === EveTurretSet.State.STATE_FIRING)
      {
        this.#recheckTimeLeft -= deltaTime;
        if (this.#recheckTimeLeft < 0)
        {
          const pair = this.#getClosestTurretAndLocator();
          if (pair.turret !== this.#activeTurret || pair.locator !== this.target?.GetLocator?.()) this.#setupFiringState();
          this.#recheckTimeLeft = 2;
        }
      }
      this.firingEffect.UpdateSynchronous?.(context);
    }
    vec3.set(EveTurretSet.#sourcePosition, this.#parentTransform[12], this.#parentTransform[13], this.#parentTransform[14]);
    this.firingEffect?.GetStartPosition?.(EveTurretSet.#sourcePosition);
    this.target?.Update?.(deltaTime, EveTurretSet.#sourcePosition);
    this.#ambientEffect()?.UpdateSyncronous?.(context, { isVisible: this.display, localToWorldTransform: this.#parentTransform });
    if (this.#turrets.length) this.turretMovementObserver?.Update?.(this.#turrets[0].worldMatrix);
    return true;
  }

  @carbon.method
  @impl.adapted
  @impl.reason("Skeleton realization is engine-owned; portable turret records may consume the same local-target tracking hook.")
  UpdateAsyncronous(context, parentData = this.#parentTransform)
  {
    const deltaTime = Number(context?.GetDeltaT?.() ?? context?.deltaTime ?? context?.deltaT ?? 0);
    const parentTransform = parentData?.transform?.length === 16 ? parentData.transform : parentData;
    if (parentTransform?.length === 16) this.UpdateTurretTransforms(parentTransform);
    if (this.#trackingInfluenceDelta !== 0)
    {
      this.trackingInfluence += this.#trackingInfluenceDelta * deltaTime;
      if (this.trackingInfluence > this.maxTrackingTime)
      {
        this.trackingInfluence = this.maxTrackingTime;
        this.#trackingInfluenceDelta = 0;
      }
      else if (this.trackingInfluence < 0)
      {
        this.trackingInfluence = 0;
        this.#trackingInfluenceDelta = 0;
      }
    }
    if (this.#delayToFadeOutTracking > 0)
    {
      this.#delayToFadeOutTracking -= deltaTime;
      if (this.#delayToFadeOutTracking <= 0)
      {
        this.#delayToFadeOutTracking = 0;
        this.#trackingInfluenceDelta = -1;
      }
    }
    if (this.#delayToFadeInTracking > 0)
    {
      this.#delayToFadeInTracking -= deltaTime;
      if (this.#delayToFadeInTracking <= 0)
      {
        this.#delayToFadeInTracking = 0;
        this.#trackingInfluenceDelta = 1;
      }
    }
    if (this.trackingInfluence !== 0)
    {
      const trackingPosition = this.target?.GetTrackingPosition?.() ?? this.target?.position;
      if (trackingPosition)
      {
        for (const turret of this.#turrets)
        {
          if (!turret.valid || !mat4.invert(EveTurretSet.#inverseTurret, turret.worldMatrix)) continue;
          vec3.transformMat4(EveTurretSet.#localTarget, trackingPosition, EveTurretSet.#inverseTurret);
          const hook = turret.UpdateTrackingPose ?? turret.source?.UpdateTrackingPose;
          hook?.call(turret.source ?? turret, EveTurretSet.#localTarget, this.trackingInfluence, this);
        }
      }
    }
    if (this.firingEffect)
    {
      this.firingEffect.SetEndPosition?.(this.target?.GetTargetPosition?.() ?? this.target?.targetPosition ?? EveTurretSet.#zero);
      for (let muzzle = 0; muzzle < this.firingEffect.GetPerMuzzleEffectCount?.(); muzzle++)
      {
        this.firingEffect.SetMuzzleTransform?.(muzzle, this.GetFiringBoneWorldTransform(muzzle, EveTurretSet.#muzzleTransform));
      }
      this.firingEffect.SetDisplayDestObject?.(this.target?.ShowDestObject?.() ?? true);
      this.firingEffect.UpdateAsynchronous?.(context);
    }
    this.#ambientEffect()?.UpdateAsyncronous?.(context, { isVisible: this.display, localToWorldTransform: this.#parentTransform });
    return true;
  }

  @carbon.method
  @impl.adapted
  @impl.reason("Renderable collection is backend-neutral; geometry and batch realization remain runtime-engine work.")
  GetRenderables(out = [])
  {
    if (!this.display) return out;
    if (this.displayEffects) this.firingEffect?.GetRenderables?.(out);
    if (this.#ambientEffect() && this.displayEffects) this.#ambientEffect().GetRenderables?.(out);
    return out;
  }

  @carbon.method
  @impl.adapted
  @impl.reason("Visibility is forwarded through backend-neutral firing and ambient graph contracts.")
  UpdateVisibility(context)
  {
    if (!this.display) return false;
    if (this.displayEffects) this.firingEffect?.UpdateVisibility?.(context);
    if (this.displayEffects) this.#ambientEffect()?.UpdateVisibility?.(context, this.#parentTransform);
    return true;
  }

  #setupFiringState()
  {
    if (this.state === EveTurretSet.State.STATE_DEACTIVE || !this.target) return false;
    const pair = this.#getClosestTurretAndLocator();
    this.#activeTurret = pair.turret;
    if (this.maxCyclingFirePos > 1)
    {
      this.currentCyclingFiresPos += this.cyclingFireGroupCount;
      if (this.currentCyclingFiresPos >= this.maxCyclingFirePos * this.cyclingFireGroupCount) this.currentCyclingFiresPos = 0;
    }
    this.randomFiringDelay = this.useRandomFiringDelay ? this.GetShotTimeVariance() * Math.random() : 0;
    const effectTotalTime = Number(this.firingEffect?.GetFiringDuration?.() ?? 0);
    const effectPeakTime = Number(this.firingEffect?.GetFiringPeakTime?.() ?? 0);
    const source = this.#parentTransform.subarray(12, 15);
    const locator = pair.locator;
    if (this.state === EveTurretSet.State.STATE_IDLE || this.state === EveTurretSet.State.STATE_RELOADING)
    {
      this.randomFiringDelay += this.maxTrackingTime;
      this.#delayToFadeInTracking = 0.0001;
    }
    const fireName = this.currentCyclingFiresPos > 0 ? `Fire0${Math.floor(this.currentCyclingFiresPos / this.cyclingFireGroupCount)}` : "Fire";
    this.#turrets.forEach((_turret, index) => this.#playTurret(index, index === this.#activeTurret ? fireName : "", "Active", this.randomFiringDelay));
    this.target.StartFireAtLocator?.(locator ?? -1, this.randomFiringDelay + effectPeakTime, effectTotalTime - effectPeakTime, source);
    const ambient = this.#ambientEffect();
    if (ambient)
    {
      ambient.SetControllerVariable?.("TurretState", this.state === EveTurretSet.State.STATE_FIRING ? EveTurretSet.State.STATE_TARGETING : this.state);
      ambient.SetControllerVariableOnInstance?.(this.#activeTurret, "TurretState", EveTurretSet.State.STATE_FIRING);
      ambient.SetControllerVariableOnInstance?.(this.#activeTurret, "FiringDelay", this.randomFiringDelay);
    }
    return true;
  }

  #getClosestTurretAndLocator()
  {
    const pair = EveTurretSet.#closestPair;
    pair.turret = EveTurretSet.INVALID_INDEX;
    pair.locator = -1;
    if (!this.#turrets.length) return pair;
    let closestAngle = -1;
    for (let index = 0; index < this.#turrets.length; index++)
    {
      const turret = this.#turrets[index];
      if (!turret.valid) continue;
      const transform = turret.worldMatrix;
      vec3.set(EveTurretSet.#turretPosition, transform[12], transform[13], transform[14]);
      const locator = this.target?.FindClosestLocator?.(EveTurretSet.#turretPosition, EveTurretSet.#locatorPosition) ?? -1;
      vec3.subtract(EveTurretSet.#targetDirection, EveTurretSet.#locatorPosition, EveTurretSet.#turretPosition);
      if (vec3.squaredLength(EveTurretSet.#targetDirection)) vec3.normalize(EveTurretSet.#targetDirection, EveTurretSet.#targetDirection);
      vec3.normalize(EveTurretSet.#turretUp, vec3.set(EveTurretSet.#turretUp, transform[4], transform[5], transform[6]));
      const angle = vec3.dot(EveTurretSet.#turretUp, EveTurretSet.#targetDirection);
      if (angle > closestAngle)
      {
        closestAngle = angle;
        pair.turret = index;
        pair.locator = locator;
      }
    }
    if (pair.turret !== EveTurretSet.INVALID_INDEX && this.chooseRandomLocator)
    {
      const transform = this.#turrets[pair.turret].worldMatrix;
      vec3.set(EveTurretSet.#turretPosition, transform[12], transform[13], transform[14]);
      const randomLocator = this.target?.FindRandomValidLocator?.(EveTurretSet.#turretPosition, EveTurretSet.#locatorPosition) ?? -1;
      if (randomLocator !== pair.locator && randomLocator !== -1)
      {
        pair.locator = randomLocator;
        closestAngle = -1;
        for (let index = 0; index < this.#turrets.length; index++)
        {
          const turret = this.#turrets[index];
          if (!turret.valid) continue;
          const turretTransform = turret.worldMatrix;
          vec3.set(EveTurretSet.#turretPosition, turretTransform[12], turretTransform[13], turretTransform[14]);
          vec3.subtract(EveTurretSet.#targetDirection, EveTurretSet.#locatorPosition, EveTurretSet.#turretPosition);
          if (vec3.squaredLength(EveTurretSet.#targetDirection)) vec3.normalize(EveTurretSet.#targetDirection, EveTurretSet.#targetDirection);
          vec3.normalize(EveTurretSet.#turretUp, vec3.set(EveTurretSet.#turretUp, turretTransform[4], turretTransform[5], turretTransform[6]));
          const angle = vec3.dot(EveTurretSet.#turretUp, EveTurretSet.#targetDirection);
          if (angle > closestAngle)
          {
            closestAngle = angle;
            pair.turret = index;
          }
        }
      }
    }
    if (pair.turret === EveTurretSet.INVALID_INDEX) pair.turret = 0;
    return pair;
  }

  #playAll(animation, loop, delay)
  {
    let duration = 0;
    for (let index = 0; index < this.#turrets.length; index++) duration = Math.max(duration, this.#playTurret(index, animation, loop, delay));
    return duration;
  }

  #playTurret(index, animation, loop, delay)
  {
    const turret = this.#turrets[index];
    if (!turret) return 0;
    return Number(turret.PlayAnimation?.(animation, loop, delay) ?? turret.controller?.PlayAnimation?.(animation, { loop, delay }) ?? 0);
  }

  #ambientEffect()
  {
    return this.ambientEffectEditingMode ? this.ambientEffect : this.generatedDistributedAmbientEffect ?? this.ambientEffect;
  }

  #setAmbientState()
  {
    this.#ambientEffect()?.SetControllerVariable?.("TurretState", this.state);
  }

  #normalizeTurret(turret)
  {
    if (turret?.localMatrix?.length === 16)
    {
      turret.worldMatrix ??= mat4.create();
      turret.localQuaternion ??= quat.create();
      turret.localPosition ??= vec4.create();
      turret.valid ??= true;
      return turret;
    }
    const localMatrix = mat4.create();
    if (turret?.length === 16) mat4.copy(localMatrix, turret);
    else if (turret?.transform?.length === 16) mat4.copy(localMatrix, turret.transform);
    return { source: turret, localMatrix, worldMatrix: mat4.clone(localMatrix), localQuaternion: quat.create(), localPosition: vec4.create(), valid: turret !== null, display: turret?.display ?? true, canFireWhenHidden: !!turret?.canFireWhenHidden };
  }

  static ImpactBehaviour = Object.freeze({
    DAMAGE_LOCATOR: 0,
    SHIELD_ELLIPSOID: 1,
    CENTER: 2,
  });

  static LOD = Object.freeze({
    LOD_INVALID: 0,
    LOD_EMPTY: 1,
    LOD_HIGHEST: 2,
    LOD_DISABLED: 3,
  });

  static State = Object.freeze({
    STATE_INVALID: 0,
    STATE_DEACTIVE: 1,
    STATE_IDLE: 2,
    STATE_TARGETING: 3,
    STATE_FIRING: 4,
    STATE_RELOADING: 5
  });

  static INVALID_INDEX = 0xffffffff;

  static MAX_TURRETS_PER_SET = 24;

  static #boneTransform = mat4.create();
  static #lowLodTransform = mat4.create();
  static #muzzleTransform = mat4.create();
  static #turretPosition = vec3.create();
  static #targetDirection = vec3.create();
  static #turretUp = vec3.create();
  static #locatorPosition = vec3.create();
  static #zero = vec3.create();
  static #sourcePosition = vec3.create();
  static #localTranslation = vec3.create();
  static #localRotation = quat.create();
  static #unitScale = vec3.fromValues(1, 1, 1);
  static #inverseTurret = mat4.create();
  static #localTarget = vec3.create();
  static #directRotation = quat.create();
  static #launcherRotation = mat4.create();
  static #unitZ = vec3.fromValues(0, 0, 1);
  static #closestPair = { turret: EveTurretSet.INVALID_INDEX, locator: -1 };

}
